package com.live.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class LiveUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.real_name
     *
     * @mbggenerated
     */
    private String real_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.birthday
     *
     * @mbggenerated
     */
    private Integer birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.card_id
     *
     * @mbggenerated
     */
    private String card_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.partner_id
     *
     * @mbggenerated
     */
    private Integer partner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.group_id
     *
     * @mbggenerated
     */
    private Integer group_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.avatar
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.add_time
     *
     * @mbggenerated
     */
    private Integer add_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.add_ip
     *
     * @mbggenerated
     */
    private String add_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.last_time
     *
     * @mbggenerated
     */
    private Integer last_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.last_ip
     *
     * @mbggenerated
     */
    private String last_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.now_money
     *
     * @mbggenerated
     */
    private BigDecimal now_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.brokerage_price
     *
     * @mbggenerated
     */
    private BigDecimal brokerage_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.integral
     *
     * @mbggenerated
     */
    private BigDecimal integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.sign_num
     *
     * @mbggenerated
     */
    private Integer sign_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.level
     *
     * @mbggenerated
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.spread_uid
     *
     * @mbggenerated
     */
    private Integer spread_uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.spread_time
     *
     * @mbggenerated
     */
    private Integer spread_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.user_type
     *
     * @mbggenerated
     */
    private String user_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.is_promoter
     *
     * @mbggenerated
     */
    private Boolean is_promoter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.pay_count
     *
     * @mbggenerated
     */
    private Integer pay_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.spread_count
     *
     * @mbggenerated
     */
    private Integer spread_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.clean_time
     *
     * @mbggenerated
     */
    private Integer clean_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.addres
     *
     * @mbggenerated
     */
    private String addres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.adminid
     *
     * @mbggenerated
     */
    private Integer adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.login_type
     *
     * @mbggenerated
     */
    private String login_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.clerk_id
     *
     * @mbggenerated
     */
    private Integer clerk_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.pay_money
     *
     * @mbggenerated
     */
    private BigDecimal pay_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_user.bind_store_time
     *
     * @mbggenerated
     */
    private Integer bind_store_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.uid
     *
     * @return the value of live_user.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.uid
     *
     * @param uid the value for live_user.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.account
     *
     * @return the value of live_user.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.account
     *
     * @param account the value for live_user.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.pwd
     *
     * @return the value of live_user.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.pwd
     *
     * @param pwd the value for live_user.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.real_name
     *
     * @return the value of live_user.real_name
     *
     * @mbggenerated
     */
    public String getReal_name() {
        return real_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.real_name
     *
     * @param real_name the value for live_user.real_name
     *
     * @mbggenerated
     */
    public void setReal_name(String real_name) {
        this.real_name = real_name == null ? null : real_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.birthday
     *
     * @return the value of live_user.birthday
     *
     * @mbggenerated
     */
    public Integer getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.birthday
     *
     * @param birthday the value for live_user.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Integer birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.card_id
     *
     * @return the value of live_user.card_id
     *
     * @mbggenerated
     */
    public String getCard_id() {
        return card_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.card_id
     *
     * @param card_id the value for live_user.card_id
     *
     * @mbggenerated
     */
    public void setCard_id(String card_id) {
        this.card_id = card_id == null ? null : card_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.mark
     *
     * @return the value of live_user.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.mark
     *
     * @param mark the value for live_user.mark
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.partner_id
     *
     * @return the value of live_user.partner_id
     *
     * @mbggenerated
     */
    public Integer getPartner_id() {
        return partner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.partner_id
     *
     * @param partner_id the value for live_user.partner_id
     *
     * @mbggenerated
     */
    public void setPartner_id(Integer partner_id) {
        this.partner_id = partner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.group_id
     *
     * @return the value of live_user.group_id
     *
     * @mbggenerated
     */
    public Integer getGroup_id() {
        return group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.group_id
     *
     * @param group_id the value for live_user.group_id
     *
     * @mbggenerated
     */
    public void setGroup_id(Integer group_id) {
        this.group_id = group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.nickname
     *
     * @return the value of live_user.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.nickname
     *
     * @param nickname the value for live_user.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.avatar
     *
     * @return the value of live_user.avatar
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.avatar
     *
     * @param avatar the value for live_user.avatar
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.phone
     *
     * @return the value of live_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.phone
     *
     * @param phone the value for live_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.add_time
     *
     * @return the value of live_user.add_time
     *
     * @mbggenerated
     */
    public Integer getAdd_time() {
        return add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.add_time
     *
     * @param add_time the value for live_user.add_time
     *
     * @mbggenerated
     */
    public void setAdd_time(Integer add_time) {
        this.add_time = add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.add_ip
     *
     * @return the value of live_user.add_ip
     *
     * @mbggenerated
     */
    public String getAdd_ip() {
        return add_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.add_ip
     *
     * @param add_ip the value for live_user.add_ip
     *
     * @mbggenerated
     */
    public void setAdd_ip(String add_ip) {
        this.add_ip = add_ip == null ? null : add_ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.last_time
     *
     * @return the value of live_user.last_time
     *
     * @mbggenerated
     */
    public Integer getLast_time() {
        return last_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.last_time
     *
     * @param last_time the value for live_user.last_time
     *
     * @mbggenerated
     */
    public void setLast_time(Integer last_time) {
        this.last_time = last_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.last_ip
     *
     * @return the value of live_user.last_ip
     *
     * @mbggenerated
     */
    public String getLast_ip() {
        return last_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.last_ip
     *
     * @param last_ip the value for live_user.last_ip
     *
     * @mbggenerated
     */
    public void setLast_ip(String last_ip) {
        this.last_ip = last_ip == null ? null : last_ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.now_money
     *
     * @return the value of live_user.now_money
     *
     * @mbggenerated
     */
    public BigDecimal getNow_money() {
        return now_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.now_money
     *
     * @param now_money the value for live_user.now_money
     *
     * @mbggenerated
     */
    public void setNow_money(BigDecimal now_money) {
        this.now_money = now_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.brokerage_price
     *
     * @return the value of live_user.brokerage_price
     *
     * @mbggenerated
     */
    public BigDecimal getBrokerage_price() {
        return brokerage_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.brokerage_price
     *
     * @param brokerage_price the value for live_user.brokerage_price
     *
     * @mbggenerated
     */
    public void setBrokerage_price(BigDecimal brokerage_price) {
        this.brokerage_price = brokerage_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.integral
     *
     * @return the value of live_user.integral
     *
     * @mbggenerated
     */
    public BigDecimal getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.integral
     *
     * @param integral the value for live_user.integral
     *
     * @mbggenerated
     */
    public void setIntegral(BigDecimal integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.sign_num
     *
     * @return the value of live_user.sign_num
     *
     * @mbggenerated
     */
    public Integer getSign_num() {
        return sign_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.sign_num
     *
     * @param sign_num the value for live_user.sign_num
     *
     * @mbggenerated
     */
    public void setSign_num(Integer sign_num) {
        this.sign_num = sign_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.status
     *
     * @return the value of live_user.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.status
     *
     * @param status the value for live_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.level
     *
     * @return the value of live_user.level
     *
     * @mbggenerated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.level
     *
     * @param level the value for live_user.level
     *
     * @mbggenerated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.spread_uid
     *
     * @return the value of live_user.spread_uid
     *
     * @mbggenerated
     */
    public Integer getSpread_uid() {
        return spread_uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.spread_uid
     *
     * @param spread_uid the value for live_user.spread_uid
     *
     * @mbggenerated
     */
    public void setSpread_uid(Integer spread_uid) {
        this.spread_uid = spread_uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.spread_time
     *
     * @return the value of live_user.spread_time
     *
     * @mbggenerated
     */
    public Integer getSpread_time() {
        return spread_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.spread_time
     *
     * @param spread_time the value for live_user.spread_time
     *
     * @mbggenerated
     */
    public void setSpread_time(Integer spread_time) {
        this.spread_time = spread_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.user_type
     *
     * @return the value of live_user.user_type
     *
     * @mbggenerated
     */
    public String getUser_type() {
        return user_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.user_type
     *
     * @param user_type the value for live_user.user_type
     *
     * @mbggenerated
     */
    public void setUser_type(String user_type) {
        this.user_type = user_type == null ? null : user_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.is_promoter
     *
     * @return the value of live_user.is_promoter
     *
     * @mbggenerated
     */
    public Boolean getIs_promoter() {
        return is_promoter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.is_promoter
     *
     * @param is_promoter the value for live_user.is_promoter
     *
     * @mbggenerated
     */
    public void setIs_promoter(Boolean is_promoter) {
        this.is_promoter = is_promoter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.pay_count
     *
     * @return the value of live_user.pay_count
     *
     * @mbggenerated
     */
    public Integer getPay_count() {
        return pay_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.pay_count
     *
     * @param pay_count the value for live_user.pay_count
     *
     * @mbggenerated
     */
    public void setPay_count(Integer pay_count) {
        this.pay_count = pay_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.spread_count
     *
     * @return the value of live_user.spread_count
     *
     * @mbggenerated
     */
    public Integer getSpread_count() {
        return spread_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.spread_count
     *
     * @param spread_count the value for live_user.spread_count
     *
     * @mbggenerated
     */
    public void setSpread_count(Integer spread_count) {
        this.spread_count = spread_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.clean_time
     *
     * @return the value of live_user.clean_time
     *
     * @mbggenerated
     */
    public Integer getClean_time() {
        return clean_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.clean_time
     *
     * @param clean_time the value for live_user.clean_time
     *
     * @mbggenerated
     */
    public void setClean_time(Integer clean_time) {
        this.clean_time = clean_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.addres
     *
     * @return the value of live_user.addres
     *
     * @mbggenerated
     */
    public String getAddres() {
        return addres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.addres
     *
     * @param addres the value for live_user.addres
     *
     * @mbggenerated
     */
    public void setAddres(String addres) {
        this.addres = addres == null ? null : addres.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.adminid
     *
     * @return the value of live_user.adminid
     *
     * @mbggenerated
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.adminid
     *
     * @param adminid the value for live_user.adminid
     *
     * @mbggenerated
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.login_type
     *
     * @return the value of live_user.login_type
     *
     * @mbggenerated
     */
    public String getLogin_type() {
        return login_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.login_type
     *
     * @param login_type the value for live_user.login_type
     *
     * @mbggenerated
     */
    public void setLogin_type(String login_type) {
        this.login_type = login_type == null ? null : login_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.clerk_id
     *
     * @return the value of live_user.clerk_id
     *
     * @mbggenerated
     */
    public Integer getClerk_id() {
        return clerk_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.clerk_id
     *
     * @param clerk_id the value for live_user.clerk_id
     *
     * @mbggenerated
     */
    public void setClerk_id(Integer clerk_id) {
        this.clerk_id = clerk_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.pay_money
     *
     * @return the value of live_user.pay_money
     *
     * @mbggenerated
     */
    public BigDecimal getPay_money() {
        return pay_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.pay_money
     *
     * @param pay_money the value for live_user.pay_money
     *
     * @mbggenerated
     */
    public void setPay_money(BigDecimal pay_money) {
        this.pay_money = pay_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_user.bind_store_time
     *
     * @return the value of live_user.bind_store_time
     *
     * @mbggenerated
     */
    public Integer getBind_store_time() {
        return bind_store_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_user.bind_store_time
     *
     * @param bind_store_time the value for live_user.bind_store_time
     *
     * @mbggenerated
     */
    public void setBind_store_time(Integer bind_store_time) {
        this.bind_store_time = bind_store_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", account=").append(account);
        sb.append(", pwd=").append(pwd);
        sb.append(", real_name=").append(real_name);
        sb.append(", birthday=").append(birthday);
        sb.append(", card_id=").append(card_id);
        sb.append(", mark=").append(mark);
        sb.append(", partner_id=").append(partner_id);
        sb.append(", group_id=").append(group_id);
        sb.append(", nickname=").append(nickname);
        sb.append(", avatar=").append(avatar);
        sb.append(", phone=").append(phone);
        sb.append(", add_time=").append(add_time);
        sb.append(", add_ip=").append(add_ip);
        sb.append(", last_time=").append(last_time);
        sb.append(", last_ip=").append(last_ip);
        sb.append(", now_money=").append(now_money);
        sb.append(", brokerage_price=").append(brokerage_price);
        sb.append(", integral=").append(integral);
        sb.append(", sign_num=").append(sign_num);
        sb.append(", status=").append(status);
        sb.append(", level=").append(level);
        sb.append(", spread_uid=").append(spread_uid);
        sb.append(", spread_time=").append(spread_time);
        sb.append(", user_type=").append(user_type);
        sb.append(", is_promoter=").append(is_promoter);
        sb.append(", pay_count=").append(pay_count);
        sb.append(", spread_count=").append(spread_count);
        sb.append(", clean_time=").append(clean_time);
        sb.append(", addres=").append(addres);
        sb.append(", adminid=").append(adminid);
        sb.append(", login_type=").append(login_type);
        sb.append(", clerk_id=").append(clerk_id);
        sb.append(", pay_money=").append(pay_money);
        sb.append(", bind_store_time=").append(bind_store_time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
