package com.live.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class LiveStoreClerk implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.wx_name
     *
     * @mbggenerated
     */
    private String wx_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.head_img
     *
     * @mbggenerated
     */
    private String head_img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.admin_id
     *
     * @mbggenerated
     */
    private Integer admin_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.store_role
     *
     * @mbggenerated
     */
    private Integer store_role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.store_status
     *
     * @mbggenerated
     */
    private Integer store_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.store_id
     *
     * @mbggenerated
     */
    private Integer store_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.parent_id
     *
     * @mbggenerated
     */
    private Integer parent_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.now_money
     *
     * @mbggenerated
     */
    private BigDecimal now_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.update_time
     *
     * @mbggenerated
     */
    private Integer update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.create_time
     *
     * @mbggenerated
     */
    private Integer create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.is_cancellation
     *
     * @mbggenerated
     */
    private Boolean is_cancellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store_clerk.cash_money
     *
     * @mbggenerated
     */
    private BigDecimal cash_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.id
     *
     * @return the value of live_store_clerk.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.id
     *
     * @param id the value for live_store_clerk.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.name
     *
     * @return the value of live_store_clerk.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.name
     *
     * @param name the value for live_store_clerk.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.wx_name
     *
     * @return the value of live_store_clerk.wx_name
     *
     * @mbggenerated
     */
    public String getWx_name() {
        return wx_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.wx_name
     *
     * @param wx_name the value for live_store_clerk.wx_name
     *
     * @mbggenerated
     */
    public void setWx_name(String wx_name) {
        this.wx_name = wx_name == null ? null : wx_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.head_img
     *
     * @return the value of live_store_clerk.head_img
     *
     * @mbggenerated
     */
    public String getHead_img() {
        return head_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.head_img
     *
     * @param head_img the value for live_store_clerk.head_img
     *
     * @mbggenerated
     */
    public void setHead_img(String head_img) {
        this.head_img = head_img == null ? null : head_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.admin_id
     *
     * @return the value of live_store_clerk.admin_id
     *
     * @mbggenerated
     */
    public Integer getAdmin_id() {
        return admin_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.admin_id
     *
     * @param admin_id the value for live_store_clerk.admin_id
     *
     * @mbggenerated
     */
    public void setAdmin_id(Integer admin_id) {
        this.admin_id = admin_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.phone
     *
     * @return the value of live_store_clerk.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.phone
     *
     * @param phone the value for live_store_clerk.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.store_role
     *
     * @return the value of live_store_clerk.store_role
     *
     * @mbggenerated
     */
    public Integer getStore_role() {
        return store_role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.store_role
     *
     * @param store_role the value for live_store_clerk.store_role
     *
     * @mbggenerated
     */
    public void setStore_role(Integer store_role) {
        this.store_role = store_role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.store_status
     *
     * @return the value of live_store_clerk.store_status
     *
     * @mbggenerated
     */
    public Integer getStore_status() {
        return store_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.store_status
     *
     * @param store_status the value for live_store_clerk.store_status
     *
     * @mbggenerated
     */
    public void setStore_status(Integer store_status) {
        this.store_status = store_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.store_id
     *
     * @return the value of live_store_clerk.store_id
     *
     * @mbggenerated
     */
    public Integer getStore_id() {
        return store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.store_id
     *
     * @param store_id the value for live_store_clerk.store_id
     *
     * @mbggenerated
     */
    public void setStore_id(Integer store_id) {
        this.store_id = store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.parent_id
     *
     * @return the value of live_store_clerk.parent_id
     *
     * @mbggenerated
     */
    public Integer getParent_id() {
        return parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.parent_id
     *
     * @param parent_id the value for live_store_clerk.parent_id
     *
     * @mbggenerated
     */
    public void setParent_id(Integer parent_id) {
        this.parent_id = parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.now_money
     *
     * @return the value of live_store_clerk.now_money
     *
     * @mbggenerated
     */
    public BigDecimal getNow_money() {
        return now_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.now_money
     *
     * @param now_money the value for live_store_clerk.now_money
     *
     * @mbggenerated
     */
    public void setNow_money(BigDecimal now_money) {
        this.now_money = now_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.openid
     *
     * @return the value of live_store_clerk.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.openid
     *
     * @param openid the value for live_store_clerk.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.update_time
     *
     * @return the value of live_store_clerk.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.update_time
     *
     * @param update_time the value for live_store_clerk.update_time
     *
     * @mbggenerated
     */
    public void setUpdate_time(Integer update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.create_time
     *
     * @return the value of live_store_clerk.create_time
     *
     * @mbggenerated
     */
    public Integer getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.create_time
     *
     * @param create_time the value for live_store_clerk.create_time
     *
     * @mbggenerated
     */
    public void setCreate_time(Integer create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.is_cancellation
     *
     * @return the value of live_store_clerk.is_cancellation
     *
     * @mbggenerated
     */
    public Boolean getIs_cancellation() {
        return is_cancellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.is_cancellation
     *
     * @param is_cancellation the value for live_store_clerk.is_cancellation
     *
     * @mbggenerated
     */
    public void setIs_cancellation(Boolean is_cancellation) {
        this.is_cancellation = is_cancellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store_clerk.cash_money
     *
     * @return the value of live_store_clerk.cash_money
     *
     * @mbggenerated
     */
    public BigDecimal getCash_money() {
        return cash_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store_clerk.cash_money
     *
     * @param cash_money the value for live_store_clerk.cash_money
     *
     * @mbggenerated
     */
    public void setCash_money(BigDecimal cash_money) {
        this.cash_money = cash_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", wx_name=").append(wx_name);
        sb.append(", head_img=").append(head_img);
        sb.append(", admin_id=").append(admin_id);
        sb.append(", phone=").append(phone);
        sb.append(", store_role=").append(store_role);
        sb.append(", store_status=").append(store_status);
        sb.append(", store_id=").append(store_id);
        sb.append(", parent_id=").append(parent_id);
        sb.append(", now_money=").append(now_money);
        sb.append(", openid=").append(openid);
        sb.append(", update_time=").append(update_time);
        sb.append(", create_time=").append(create_time);
        sb.append(", is_cancellation=").append(is_cancellation);
        sb.append(", cash_money=").append(cash_money);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}