package com.live.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class LiveUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live_user
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live_user
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live_user
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    public LiveUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table live_user
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidIsNull() {
            addCriterion("`uid` is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("`uid` is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("`uid` =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("`uid` <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("`uid` >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("`uid` >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("`uid` <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("`uid` <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("`uid` in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("`uid` not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("`uid` between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("`uid` not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("account is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("account is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("account =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("account <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("account >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("account >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("account <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("account <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("account like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("account not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("account in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("account not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("account between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("account not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andPwdIsNull() {
            addCriterion("pwd is null");
            return (Criteria) this;
        }

        public Criteria andPwdIsNotNull() {
            addCriterion("pwd is not null");
            return (Criteria) this;
        }

        public Criteria andPwdEqualTo(String value) {
            addCriterion("pwd =", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotEqualTo(String value) {
            addCriterion("pwd <>", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThan(String value) {
            addCriterion("pwd >", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThanOrEqualTo(String value) {
            addCriterion("pwd >=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThan(String value) {
            addCriterion("pwd <", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThanOrEqualTo(String value) {
            addCriterion("pwd <=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLike(String value) {
            addCriterion("pwd like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotLike(String value) {
            addCriterion("pwd not like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdIn(List<String> values) {
            addCriterion("pwd in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotIn(List<String> values) {
            addCriterion("pwd not in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdBetween(String value1, String value2) {
            addCriterion("pwd between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotBetween(String value1, String value2) {
            addCriterion("pwd not between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andReal_nameIsNull() {
            addCriterion("real_name is null");
            return (Criteria) this;
        }

        public Criteria andReal_nameIsNotNull() {
            addCriterion("real_name is not null");
            return (Criteria) this;
        }

        public Criteria andReal_nameEqualTo(String value) {
            addCriterion("real_name =", value, "real_name");
            return (Criteria) this;
        }

        public Criteria andReal_nameNotEqualTo(String value) {
            addCriterion("real_name <>", value, "real_name");
            return (Criteria) this;
        }

        public Criteria andReal_nameGreaterThan(String value) {
            addCriterion("real_name >", value, "real_name");
            return (Criteria) this;
        }

        public Criteria andReal_nameGreaterThanOrEqualTo(String value) {
            addCriterion("real_name >=", value, "real_name");
            return (Criteria) this;
        }

        public Criteria andReal_nameLessThan(String value) {
            addCriterion("real_name <", value, "real_name");
            return (Criteria) this;
        }

        public Criteria andReal_nameLessThanOrEqualTo(String value) {
            addCriterion("real_name <=", value, "real_name");
            return (Criteria) this;
        }

        public Criteria andReal_nameLike(String value) {
            addCriterion("real_name like", value, "real_name");
            return (Criteria) this;
        }

        public Criteria andReal_nameNotLike(String value) {
            addCriterion("real_name not like", value, "real_name");
            return (Criteria) this;
        }

        public Criteria andReal_nameIn(List<String> values) {
            addCriterion("real_name in", values, "real_name");
            return (Criteria) this;
        }

        public Criteria andReal_nameNotIn(List<String> values) {
            addCriterion("real_name not in", values, "real_name");
            return (Criteria) this;
        }

        public Criteria andReal_nameBetween(String value1, String value2) {
            addCriterion("real_name between", value1, value2, "real_name");
            return (Criteria) this;
        }

        public Criteria andReal_nameNotBetween(String value1, String value2) {
            addCriterion("real_name not between", value1, value2, "real_name");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Integer value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Integer value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Integer value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Integer value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Integer value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Integer value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Integer> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Integer> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Integer value1, Integer value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Integer value1, Integer value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andCard_idIsNull() {
            addCriterion("card_id is null");
            return (Criteria) this;
        }

        public Criteria andCard_idIsNotNull() {
            addCriterion("card_id is not null");
            return (Criteria) this;
        }

        public Criteria andCard_idEqualTo(String value) {
            addCriterion("card_id =", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idNotEqualTo(String value) {
            addCriterion("card_id <>", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idGreaterThan(String value) {
            addCriterion("card_id >", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idGreaterThanOrEqualTo(String value) {
            addCriterion("card_id >=", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idLessThan(String value) {
            addCriterion("card_id <", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idLessThanOrEqualTo(String value) {
            addCriterion("card_id <=", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idLike(String value) {
            addCriterion("card_id like", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idNotLike(String value) {
            addCriterion("card_id not like", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idIn(List<String> values) {
            addCriterion("card_id in", values, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idNotIn(List<String> values) {
            addCriterion("card_id not in", values, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idBetween(String value1, String value2) {
            addCriterion("card_id between", value1, value2, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idNotBetween(String value1, String value2) {
            addCriterion("card_id not between", value1, value2, "card_id");
            return (Criteria) this;
        }

        public Criteria andMarkIsNull() {
            addCriterion("mark is null");
            return (Criteria) this;
        }

        public Criteria andMarkIsNotNull() {
            addCriterion("mark is not null");
            return (Criteria) this;
        }

        public Criteria andMarkEqualTo(String value) {
            addCriterion("mark =", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotEqualTo(String value) {
            addCriterion("mark <>", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkGreaterThan(String value) {
            addCriterion("mark >", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkGreaterThanOrEqualTo(String value) {
            addCriterion("mark >=", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLessThan(String value) {
            addCriterion("mark <", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLessThanOrEqualTo(String value) {
            addCriterion("mark <=", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLike(String value) {
            addCriterion("mark like", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotLike(String value) {
            addCriterion("mark not like", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkIn(List<String> values) {
            addCriterion("mark in", values, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotIn(List<String> values) {
            addCriterion("mark not in", values, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkBetween(String value1, String value2) {
            addCriterion("mark between", value1, value2, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotBetween(String value1, String value2) {
            addCriterion("mark not between", value1, value2, "mark");
            return (Criteria) this;
        }

        public Criteria andPartner_idIsNull() {
            addCriterion("partner_id is null");
            return (Criteria) this;
        }

        public Criteria andPartner_idIsNotNull() {
            addCriterion("partner_id is not null");
            return (Criteria) this;
        }

        public Criteria andPartner_idEqualTo(Integer value) {
            addCriterion("partner_id =", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotEqualTo(Integer value) {
            addCriterion("partner_id <>", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idGreaterThan(Integer value) {
            addCriterion("partner_id >", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("partner_id >=", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idLessThan(Integer value) {
            addCriterion("partner_id <", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idLessThanOrEqualTo(Integer value) {
            addCriterion("partner_id <=", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idIn(List<Integer> values) {
            addCriterion("partner_id in", values, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotIn(List<Integer> values) {
            addCriterion("partner_id not in", values, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idBetween(Integer value1, Integer value2) {
            addCriterion("partner_id between", value1, value2, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotBetween(Integer value1, Integer value2) {
            addCriterion("partner_id not between", value1, value2, "partner_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroup_idIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroup_idEqualTo(Integer value) {
            addCriterion("group_id =", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idNotEqualTo(Integer value) {
            addCriterion("group_id <>", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idGreaterThan(Integer value) {
            addCriterion("group_id >", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("group_id >=", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idLessThan(Integer value) {
            addCriterion("group_id <", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idLessThanOrEqualTo(Integer value) {
            addCriterion("group_id <=", value, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idIn(List<Integer> values) {
            addCriterion("group_id in", values, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idNotIn(List<Integer> values) {
            addCriterion("group_id not in", values, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idBetween(Integer value1, Integer value2) {
            addCriterion("group_id between", value1, value2, "group_id");
            return (Criteria) this;
        }

        public Criteria andGroup_idNotBetween(Integer value1, Integer value2) {
            addCriterion("group_id not between", value1, value2, "group_id");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNull() {
            addCriterion("avatar is null");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNotNull() {
            addCriterion("avatar is not null");
            return (Criteria) this;
        }

        public Criteria andAvatarEqualTo(String value) {
            addCriterion("avatar =", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotEqualTo(String value) {
            addCriterion("avatar <>", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThan(String value) {
            addCriterion("avatar >", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThanOrEqualTo(String value) {
            addCriterion("avatar >=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThan(String value) {
            addCriterion("avatar <", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThanOrEqualTo(String value) {
            addCriterion("avatar <=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLike(String value) {
            addCriterion("avatar like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotLike(String value) {
            addCriterion("avatar not like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarIn(List<String> values) {
            addCriterion("avatar in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotIn(List<String> values) {
            addCriterion("avatar not in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarBetween(String value1, String value2) {
            addCriterion("avatar between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotBetween(String value1, String value2) {
            addCriterion("avatar not between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andAdd_timeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAdd_timeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAdd_timeEqualTo(Integer value) {
            addCriterion("add_time =", value, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeNotEqualTo(Integer value) {
            addCriterion("add_time <>", value, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeGreaterThan(Integer value) {
            addCriterion("add_time >", value, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeGreaterThanOrEqualTo(Integer value) {
            addCriterion("add_time >=", value, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeLessThan(Integer value) {
            addCriterion("add_time <", value, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeLessThanOrEqualTo(Integer value) {
            addCriterion("add_time <=", value, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeIn(List<Integer> values) {
            addCriterion("add_time in", values, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeNotIn(List<Integer> values) {
            addCriterion("add_time not in", values, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeBetween(Integer value1, Integer value2) {
            addCriterion("add_time between", value1, value2, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeNotBetween(Integer value1, Integer value2) {
            addCriterion("add_time not between", value1, value2, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_ipIsNull() {
            addCriterion("add_ip is null");
            return (Criteria) this;
        }

        public Criteria andAdd_ipIsNotNull() {
            addCriterion("add_ip is not null");
            return (Criteria) this;
        }

        public Criteria andAdd_ipEqualTo(String value) {
            addCriterion("add_ip =", value, "add_ip");
            return (Criteria) this;
        }

        public Criteria andAdd_ipNotEqualTo(String value) {
            addCriterion("add_ip <>", value, "add_ip");
            return (Criteria) this;
        }

        public Criteria andAdd_ipGreaterThan(String value) {
            addCriterion("add_ip >", value, "add_ip");
            return (Criteria) this;
        }

        public Criteria andAdd_ipGreaterThanOrEqualTo(String value) {
            addCriterion("add_ip >=", value, "add_ip");
            return (Criteria) this;
        }

        public Criteria andAdd_ipLessThan(String value) {
            addCriterion("add_ip <", value, "add_ip");
            return (Criteria) this;
        }

        public Criteria andAdd_ipLessThanOrEqualTo(String value) {
            addCriterion("add_ip <=", value, "add_ip");
            return (Criteria) this;
        }

        public Criteria andAdd_ipLike(String value) {
            addCriterion("add_ip like", value, "add_ip");
            return (Criteria) this;
        }

        public Criteria andAdd_ipNotLike(String value) {
            addCriterion("add_ip not like", value, "add_ip");
            return (Criteria) this;
        }

        public Criteria andAdd_ipIn(List<String> values) {
            addCriterion("add_ip in", values, "add_ip");
            return (Criteria) this;
        }

        public Criteria andAdd_ipNotIn(List<String> values) {
            addCriterion("add_ip not in", values, "add_ip");
            return (Criteria) this;
        }

        public Criteria andAdd_ipBetween(String value1, String value2) {
            addCriterion("add_ip between", value1, value2, "add_ip");
            return (Criteria) this;
        }

        public Criteria andAdd_ipNotBetween(String value1, String value2) {
            addCriterion("add_ip not between", value1, value2, "add_ip");
            return (Criteria) this;
        }

        public Criteria andLast_timeIsNull() {
            addCriterion("last_time is null");
            return (Criteria) this;
        }

        public Criteria andLast_timeIsNotNull() {
            addCriterion("last_time is not null");
            return (Criteria) this;
        }

        public Criteria andLast_timeEqualTo(Integer value) {
            addCriterion("last_time =", value, "last_time");
            return (Criteria) this;
        }

        public Criteria andLast_timeNotEqualTo(Integer value) {
            addCriterion("last_time <>", value, "last_time");
            return (Criteria) this;
        }

        public Criteria andLast_timeGreaterThan(Integer value) {
            addCriterion("last_time >", value, "last_time");
            return (Criteria) this;
        }

        public Criteria andLast_timeGreaterThanOrEqualTo(Integer value) {
            addCriterion("last_time >=", value, "last_time");
            return (Criteria) this;
        }

        public Criteria andLast_timeLessThan(Integer value) {
            addCriterion("last_time <", value, "last_time");
            return (Criteria) this;
        }

        public Criteria andLast_timeLessThanOrEqualTo(Integer value) {
            addCriterion("last_time <=", value, "last_time");
            return (Criteria) this;
        }

        public Criteria andLast_timeIn(List<Integer> values) {
            addCriterion("last_time in", values, "last_time");
            return (Criteria) this;
        }

        public Criteria andLast_timeNotIn(List<Integer> values) {
            addCriterion("last_time not in", values, "last_time");
            return (Criteria) this;
        }

        public Criteria andLast_timeBetween(Integer value1, Integer value2) {
            addCriterion("last_time between", value1, value2, "last_time");
            return (Criteria) this;
        }

        public Criteria andLast_timeNotBetween(Integer value1, Integer value2) {
            addCriterion("last_time not between", value1, value2, "last_time");
            return (Criteria) this;
        }

        public Criteria andLast_ipIsNull() {
            addCriterion("last_ip is null");
            return (Criteria) this;
        }

        public Criteria andLast_ipIsNotNull() {
            addCriterion("last_ip is not null");
            return (Criteria) this;
        }

        public Criteria andLast_ipEqualTo(String value) {
            addCriterion("last_ip =", value, "last_ip");
            return (Criteria) this;
        }

        public Criteria andLast_ipNotEqualTo(String value) {
            addCriterion("last_ip <>", value, "last_ip");
            return (Criteria) this;
        }

        public Criteria andLast_ipGreaterThan(String value) {
            addCriterion("last_ip >", value, "last_ip");
            return (Criteria) this;
        }

        public Criteria andLast_ipGreaterThanOrEqualTo(String value) {
            addCriterion("last_ip >=", value, "last_ip");
            return (Criteria) this;
        }

        public Criteria andLast_ipLessThan(String value) {
            addCriterion("last_ip <", value, "last_ip");
            return (Criteria) this;
        }

        public Criteria andLast_ipLessThanOrEqualTo(String value) {
            addCriterion("last_ip <=", value, "last_ip");
            return (Criteria) this;
        }

        public Criteria andLast_ipLike(String value) {
            addCriterion("last_ip like", value, "last_ip");
            return (Criteria) this;
        }

        public Criteria andLast_ipNotLike(String value) {
            addCriterion("last_ip not like", value, "last_ip");
            return (Criteria) this;
        }

        public Criteria andLast_ipIn(List<String> values) {
            addCriterion("last_ip in", values, "last_ip");
            return (Criteria) this;
        }

        public Criteria andLast_ipNotIn(List<String> values) {
            addCriterion("last_ip not in", values, "last_ip");
            return (Criteria) this;
        }

        public Criteria andLast_ipBetween(String value1, String value2) {
            addCriterion("last_ip between", value1, value2, "last_ip");
            return (Criteria) this;
        }

        public Criteria andLast_ipNotBetween(String value1, String value2) {
            addCriterion("last_ip not between", value1, value2, "last_ip");
            return (Criteria) this;
        }

        public Criteria andNow_moneyIsNull() {
            addCriterion("now_money is null");
            return (Criteria) this;
        }

        public Criteria andNow_moneyIsNotNull() {
            addCriterion("now_money is not null");
            return (Criteria) this;
        }

        public Criteria andNow_moneyEqualTo(BigDecimal value) {
            addCriterion("now_money =", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyNotEqualTo(BigDecimal value) {
            addCriterion("now_money <>", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyGreaterThan(BigDecimal value) {
            addCriterion("now_money >", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("now_money >=", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyLessThan(BigDecimal value) {
            addCriterion("now_money <", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("now_money <=", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyIn(List<BigDecimal> values) {
            addCriterion("now_money in", values, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyNotIn(List<BigDecimal> values) {
            addCriterion("now_money not in", values, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("now_money between", value1, value2, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("now_money not between", value1, value2, "now_money");
            return (Criteria) this;
        }

        public Criteria andBrokerage_priceIsNull() {
            addCriterion("brokerage_price is null");
            return (Criteria) this;
        }

        public Criteria andBrokerage_priceIsNotNull() {
            addCriterion("brokerage_price is not null");
            return (Criteria) this;
        }

        public Criteria andBrokerage_priceEqualTo(BigDecimal value) {
            addCriterion("brokerage_price =", value, "brokerage_price");
            return (Criteria) this;
        }

        public Criteria andBrokerage_priceNotEqualTo(BigDecimal value) {
            addCriterion("brokerage_price <>", value, "brokerage_price");
            return (Criteria) this;
        }

        public Criteria andBrokerage_priceGreaterThan(BigDecimal value) {
            addCriterion("brokerage_price >", value, "brokerage_price");
            return (Criteria) this;
        }

        public Criteria andBrokerage_priceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("brokerage_price >=", value, "brokerage_price");
            return (Criteria) this;
        }

        public Criteria andBrokerage_priceLessThan(BigDecimal value) {
            addCriterion("brokerage_price <", value, "brokerage_price");
            return (Criteria) this;
        }

        public Criteria andBrokerage_priceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("brokerage_price <=", value, "brokerage_price");
            return (Criteria) this;
        }

        public Criteria andBrokerage_priceIn(List<BigDecimal> values) {
            addCriterion("brokerage_price in", values, "brokerage_price");
            return (Criteria) this;
        }

        public Criteria andBrokerage_priceNotIn(List<BigDecimal> values) {
            addCriterion("brokerage_price not in", values, "brokerage_price");
            return (Criteria) this;
        }

        public Criteria andBrokerage_priceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("brokerage_price between", value1, value2, "brokerage_price");
            return (Criteria) this;
        }

        public Criteria andBrokerage_priceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("brokerage_price not between", value1, value2, "brokerage_price");
            return (Criteria) this;
        }

        public Criteria andIntegralIsNull() {
            addCriterion("integral is null");
            return (Criteria) this;
        }

        public Criteria andIntegralIsNotNull() {
            addCriterion("integral is not null");
            return (Criteria) this;
        }

        public Criteria andIntegralEqualTo(BigDecimal value) {
            addCriterion("integral =", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralNotEqualTo(BigDecimal value) {
            addCriterion("integral <>", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralGreaterThan(BigDecimal value) {
            addCriterion("integral >", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("integral >=", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralLessThan(BigDecimal value) {
            addCriterion("integral <", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralLessThanOrEqualTo(BigDecimal value) {
            addCriterion("integral <=", value, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralIn(List<BigDecimal> values) {
            addCriterion("integral in", values, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralNotIn(List<BigDecimal> values) {
            addCriterion("integral not in", values, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("integral between", value1, value2, "integral");
            return (Criteria) this;
        }

        public Criteria andIntegralNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("integral not between", value1, value2, "integral");
            return (Criteria) this;
        }

        public Criteria andSign_numIsNull() {
            addCriterion("sign_num is null");
            return (Criteria) this;
        }

        public Criteria andSign_numIsNotNull() {
            addCriterion("sign_num is not null");
            return (Criteria) this;
        }

        public Criteria andSign_numEqualTo(Integer value) {
            addCriterion("sign_num =", value, "sign_num");
            return (Criteria) this;
        }

        public Criteria andSign_numNotEqualTo(Integer value) {
            addCriterion("sign_num <>", value, "sign_num");
            return (Criteria) this;
        }

        public Criteria andSign_numGreaterThan(Integer value) {
            addCriterion("sign_num >", value, "sign_num");
            return (Criteria) this;
        }

        public Criteria andSign_numGreaterThanOrEqualTo(Integer value) {
            addCriterion("sign_num >=", value, "sign_num");
            return (Criteria) this;
        }

        public Criteria andSign_numLessThan(Integer value) {
            addCriterion("sign_num <", value, "sign_num");
            return (Criteria) this;
        }

        public Criteria andSign_numLessThanOrEqualTo(Integer value) {
            addCriterion("sign_num <=", value, "sign_num");
            return (Criteria) this;
        }

        public Criteria andSign_numIn(List<Integer> values) {
            addCriterion("sign_num in", values, "sign_num");
            return (Criteria) this;
        }

        public Criteria andSign_numNotIn(List<Integer> values) {
            addCriterion("sign_num not in", values, "sign_num");
            return (Criteria) this;
        }

        public Criteria andSign_numBetween(Integer value1, Integer value2) {
            addCriterion("sign_num between", value1, value2, "sign_num");
            return (Criteria) this;
        }

        public Criteria andSign_numNotBetween(Integer value1, Integer value2) {
            addCriterion("sign_num not between", value1, value2, "sign_num");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("`level` is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("`level` is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Byte value) {
            addCriterion("`level` =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Byte value) {
            addCriterion("`level` <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Byte value) {
            addCriterion("`level` >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Byte value) {
            addCriterion("`level` >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Byte value) {
            addCriterion("`level` <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Byte value) {
            addCriterion("`level` <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Byte> values) {
            addCriterion("`level` in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Byte> values) {
            addCriterion("`level` not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Byte value1, Byte value2) {
            addCriterion("`level` between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Byte value1, Byte value2) {
            addCriterion("`level` not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andSpread_uidIsNull() {
            addCriterion("spread_uid is null");
            return (Criteria) this;
        }

        public Criteria andSpread_uidIsNotNull() {
            addCriterion("spread_uid is not null");
            return (Criteria) this;
        }

        public Criteria andSpread_uidEqualTo(Integer value) {
            addCriterion("spread_uid =", value, "spread_uid");
            return (Criteria) this;
        }

        public Criteria andSpread_uidNotEqualTo(Integer value) {
            addCriterion("spread_uid <>", value, "spread_uid");
            return (Criteria) this;
        }

        public Criteria andSpread_uidGreaterThan(Integer value) {
            addCriterion("spread_uid >", value, "spread_uid");
            return (Criteria) this;
        }

        public Criteria andSpread_uidGreaterThanOrEqualTo(Integer value) {
            addCriterion("spread_uid >=", value, "spread_uid");
            return (Criteria) this;
        }

        public Criteria andSpread_uidLessThan(Integer value) {
            addCriterion("spread_uid <", value, "spread_uid");
            return (Criteria) this;
        }

        public Criteria andSpread_uidLessThanOrEqualTo(Integer value) {
            addCriterion("spread_uid <=", value, "spread_uid");
            return (Criteria) this;
        }

        public Criteria andSpread_uidIn(List<Integer> values) {
            addCriterion("spread_uid in", values, "spread_uid");
            return (Criteria) this;
        }

        public Criteria andSpread_uidNotIn(List<Integer> values) {
            addCriterion("spread_uid not in", values, "spread_uid");
            return (Criteria) this;
        }

        public Criteria andSpread_uidBetween(Integer value1, Integer value2) {
            addCriterion("spread_uid between", value1, value2, "spread_uid");
            return (Criteria) this;
        }

        public Criteria andSpread_uidNotBetween(Integer value1, Integer value2) {
            addCriterion("spread_uid not between", value1, value2, "spread_uid");
            return (Criteria) this;
        }

        public Criteria andSpread_timeIsNull() {
            addCriterion("spread_time is null");
            return (Criteria) this;
        }

        public Criteria andSpread_timeIsNotNull() {
            addCriterion("spread_time is not null");
            return (Criteria) this;
        }

        public Criteria andSpread_timeEqualTo(Integer value) {
            addCriterion("spread_time =", value, "spread_time");
            return (Criteria) this;
        }

        public Criteria andSpread_timeNotEqualTo(Integer value) {
            addCriterion("spread_time <>", value, "spread_time");
            return (Criteria) this;
        }

        public Criteria andSpread_timeGreaterThan(Integer value) {
            addCriterion("spread_time >", value, "spread_time");
            return (Criteria) this;
        }

        public Criteria andSpread_timeGreaterThanOrEqualTo(Integer value) {
            addCriterion("spread_time >=", value, "spread_time");
            return (Criteria) this;
        }

        public Criteria andSpread_timeLessThan(Integer value) {
            addCriterion("spread_time <", value, "spread_time");
            return (Criteria) this;
        }

        public Criteria andSpread_timeLessThanOrEqualTo(Integer value) {
            addCriterion("spread_time <=", value, "spread_time");
            return (Criteria) this;
        }

        public Criteria andSpread_timeIn(List<Integer> values) {
            addCriterion("spread_time in", values, "spread_time");
            return (Criteria) this;
        }

        public Criteria andSpread_timeNotIn(List<Integer> values) {
            addCriterion("spread_time not in", values, "spread_time");
            return (Criteria) this;
        }

        public Criteria andSpread_timeBetween(Integer value1, Integer value2) {
            addCriterion("spread_time between", value1, value2, "spread_time");
            return (Criteria) this;
        }

        public Criteria andSpread_timeNotBetween(Integer value1, Integer value2) {
            addCriterion("spread_time not between", value1, value2, "spread_time");
            return (Criteria) this;
        }

        public Criteria andUser_typeIsNull() {
            addCriterion("user_type is null");
            return (Criteria) this;
        }

        public Criteria andUser_typeIsNotNull() {
            addCriterion("user_type is not null");
            return (Criteria) this;
        }

        public Criteria andUser_typeEqualTo(String value) {
            addCriterion("user_type =", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeNotEqualTo(String value) {
            addCriterion("user_type <>", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeGreaterThan(String value) {
            addCriterion("user_type >", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeGreaterThanOrEqualTo(String value) {
            addCriterion("user_type >=", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeLessThan(String value) {
            addCriterion("user_type <", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeLessThanOrEqualTo(String value) {
            addCriterion("user_type <=", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeLike(String value) {
            addCriterion("user_type like", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeNotLike(String value) {
            addCriterion("user_type not like", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeIn(List<String> values) {
            addCriterion("user_type in", values, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeNotIn(List<String> values) {
            addCriterion("user_type not in", values, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeBetween(String value1, String value2) {
            addCriterion("user_type between", value1, value2, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeNotBetween(String value1, String value2) {
            addCriterion("user_type not between", value1, value2, "user_type");
            return (Criteria) this;
        }

        public Criteria andIs_promoterIsNull() {
            addCriterion("is_promoter is null");
            return (Criteria) this;
        }

        public Criteria andIs_promoterIsNotNull() {
            addCriterion("is_promoter is not null");
            return (Criteria) this;
        }

        public Criteria andIs_promoterEqualTo(Integer value) {
            addCriterion("is_promoter =", value, "is_promoter");
            return (Criteria) this;
        }

        public Criteria andIs_promoterNotEqualTo(Integer value) {
            addCriterion("is_promoter <>", value, "is_promoter");
            return (Criteria) this;
        }

        public Criteria andIs_promoterGreaterThan(Integer value) {
            addCriterion("is_promoter >", value, "is_promoter");
            return (Criteria) this;
        }

        public Criteria andIs_promoterGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_promoter >=", value, "is_promoter");
            return (Criteria) this;
        }

        public Criteria andIs_promoterLessThan(Integer value) {
            addCriterion("is_promoter <", value, "is_promoter");
            return (Criteria) this;
        }

        public Criteria andIs_promoterLessThanOrEqualTo(Integer value) {
            addCriterion("is_promoter <=", value, "is_promoter");
            return (Criteria) this;
        }

        public Criteria andIs_promoterIn(List<Integer> values) {
            addCriterion("is_promoter in", values, "is_promoter");
            return (Criteria) this;
        }

        public Criteria andIs_promoterNotIn(List<Integer> values) {
            addCriterion("is_promoter not in", values, "is_promoter");
            return (Criteria) this;
        }

        public Criteria andIs_promoterBetween(Integer value1, Integer value2) {
            addCriterion("is_promoter between", value1, value2, "is_promoter");
            return (Criteria) this;
        }

        public Criteria andIs_promoterNotBetween(Integer value1, Integer value2) {
            addCriterion("is_promoter not between", value1, value2, "is_promoter");
            return (Criteria) this;
        }

        public Criteria andPay_countIsNull() {
            addCriterion("pay_count is null");
            return (Criteria) this;
        }

        public Criteria andPay_countIsNotNull() {
            addCriterion("pay_count is not null");
            return (Criteria) this;
        }

        public Criteria andPay_countEqualTo(Integer value) {
            addCriterion("pay_count =", value, "pay_count");
            return (Criteria) this;
        }

        public Criteria andPay_countNotEqualTo(Integer value) {
            addCriterion("pay_count <>", value, "pay_count");
            return (Criteria) this;
        }

        public Criteria andPay_countGreaterThan(Integer value) {
            addCriterion("pay_count >", value, "pay_count");
            return (Criteria) this;
        }

        public Criteria andPay_countGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_count >=", value, "pay_count");
            return (Criteria) this;
        }

        public Criteria andPay_countLessThan(Integer value) {
            addCriterion("pay_count <", value, "pay_count");
            return (Criteria) this;
        }

        public Criteria andPay_countLessThanOrEqualTo(Integer value) {
            addCriterion("pay_count <=", value, "pay_count");
            return (Criteria) this;
        }

        public Criteria andPay_countIn(List<Integer> values) {
            addCriterion("pay_count in", values, "pay_count");
            return (Criteria) this;
        }

        public Criteria andPay_countNotIn(List<Integer> values) {
            addCriterion("pay_count not in", values, "pay_count");
            return (Criteria) this;
        }

        public Criteria andPay_countBetween(Integer value1, Integer value2) {
            addCriterion("pay_count between", value1, value2, "pay_count");
            return (Criteria) this;
        }

        public Criteria andPay_countNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_count not between", value1, value2, "pay_count");
            return (Criteria) this;
        }

        public Criteria andSpread_countIsNull() {
            addCriterion("spread_count is null");
            return (Criteria) this;
        }

        public Criteria andSpread_countIsNotNull() {
            addCriterion("spread_count is not null");
            return (Criteria) this;
        }

        public Criteria andSpread_countEqualTo(Integer value) {
            addCriterion("spread_count =", value, "spread_count");
            return (Criteria) this;
        }

        public Criteria andSpread_countNotEqualTo(Integer value) {
            addCriterion("spread_count <>", value, "spread_count");
            return (Criteria) this;
        }

        public Criteria andSpread_countGreaterThan(Integer value) {
            addCriterion("spread_count >", value, "spread_count");
            return (Criteria) this;
        }

        public Criteria andSpread_countGreaterThanOrEqualTo(Integer value) {
            addCriterion("spread_count >=", value, "spread_count");
            return (Criteria) this;
        }

        public Criteria andSpread_countLessThan(Integer value) {
            addCriterion("spread_count <", value, "spread_count");
            return (Criteria) this;
        }

        public Criteria andSpread_countLessThanOrEqualTo(Integer value) {
            addCriterion("spread_count <=", value, "spread_count");
            return (Criteria) this;
        }

        public Criteria andSpread_countIn(List<Integer> values) {
            addCriterion("spread_count in", values, "spread_count");
            return (Criteria) this;
        }

        public Criteria andSpread_countNotIn(List<Integer> values) {
            addCriterion("spread_count not in", values, "spread_count");
            return (Criteria) this;
        }

        public Criteria andSpread_countBetween(Integer value1, Integer value2) {
            addCriterion("spread_count between", value1, value2, "spread_count");
            return (Criteria) this;
        }

        public Criteria andSpread_countNotBetween(Integer value1, Integer value2) {
            addCriterion("spread_count not between", value1, value2, "spread_count");
            return (Criteria) this;
        }

        public Criteria andClean_timeIsNull() {
            addCriterion("clean_time is null");
            return (Criteria) this;
        }

        public Criteria andClean_timeIsNotNull() {
            addCriterion("clean_time is not null");
            return (Criteria) this;
        }

        public Criteria andClean_timeEqualTo(Integer value) {
            addCriterion("clean_time =", value, "clean_time");
            return (Criteria) this;
        }

        public Criteria andClean_timeNotEqualTo(Integer value) {
            addCriterion("clean_time <>", value, "clean_time");
            return (Criteria) this;
        }

        public Criteria andClean_timeGreaterThan(Integer value) {
            addCriterion("clean_time >", value, "clean_time");
            return (Criteria) this;
        }

        public Criteria andClean_timeGreaterThanOrEqualTo(Integer value) {
            addCriterion("clean_time >=", value, "clean_time");
            return (Criteria) this;
        }

        public Criteria andClean_timeLessThan(Integer value) {
            addCriterion("clean_time <", value, "clean_time");
            return (Criteria) this;
        }

        public Criteria andClean_timeLessThanOrEqualTo(Integer value) {
            addCriterion("clean_time <=", value, "clean_time");
            return (Criteria) this;
        }

        public Criteria andClean_timeIn(List<Integer> values) {
            addCriterion("clean_time in", values, "clean_time");
            return (Criteria) this;
        }

        public Criteria andClean_timeNotIn(List<Integer> values) {
            addCriterion("clean_time not in", values, "clean_time");
            return (Criteria) this;
        }

        public Criteria andClean_timeBetween(Integer value1, Integer value2) {
            addCriterion("clean_time between", value1, value2, "clean_time");
            return (Criteria) this;
        }

        public Criteria andClean_timeNotBetween(Integer value1, Integer value2) {
            addCriterion("clean_time not between", value1, value2, "clean_time");
            return (Criteria) this;
        }

        public Criteria andAddresIsNull() {
            addCriterion("addres is null");
            return (Criteria) this;
        }

        public Criteria andAddresIsNotNull() {
            addCriterion("addres is not null");
            return (Criteria) this;
        }

        public Criteria andAddresEqualTo(String value) {
            addCriterion("addres =", value, "addres");
            return (Criteria) this;
        }

        public Criteria andAddresNotEqualTo(String value) {
            addCriterion("addres <>", value, "addres");
            return (Criteria) this;
        }

        public Criteria andAddresGreaterThan(String value) {
            addCriterion("addres >", value, "addres");
            return (Criteria) this;
        }

        public Criteria andAddresGreaterThanOrEqualTo(String value) {
            addCriterion("addres >=", value, "addres");
            return (Criteria) this;
        }

        public Criteria andAddresLessThan(String value) {
            addCriterion("addres <", value, "addres");
            return (Criteria) this;
        }

        public Criteria andAddresLessThanOrEqualTo(String value) {
            addCriterion("addres <=", value, "addres");
            return (Criteria) this;
        }

        public Criteria andAddresLike(String value) {
            addCriterion("addres like", value, "addres");
            return (Criteria) this;
        }

        public Criteria andAddresNotLike(String value) {
            addCriterion("addres not like", value, "addres");
            return (Criteria) this;
        }

        public Criteria andAddresIn(List<String> values) {
            addCriterion("addres in", values, "addres");
            return (Criteria) this;
        }

        public Criteria andAddresNotIn(List<String> values) {
            addCriterion("addres not in", values, "addres");
            return (Criteria) this;
        }

        public Criteria andAddresBetween(String value1, String value2) {
            addCriterion("addres between", value1, value2, "addres");
            return (Criteria) this;
        }

        public Criteria andAddresNotBetween(String value1, String value2) {
            addCriterion("addres not between", value1, value2, "addres");
            return (Criteria) this;
        }

        public Criteria andAdminidIsNull() {
            addCriterion("adminid is null");
            return (Criteria) this;
        }

        public Criteria andAdminidIsNotNull() {
            addCriterion("adminid is not null");
            return (Criteria) this;
        }

        public Criteria andAdminidEqualTo(Integer value) {
            addCriterion("adminid =", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotEqualTo(Integer value) {
            addCriterion("adminid <>", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidGreaterThan(Integer value) {
            addCriterion("adminid >", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidGreaterThanOrEqualTo(Integer value) {
            addCriterion("adminid >=", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidLessThan(Integer value) {
            addCriterion("adminid <", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidLessThanOrEqualTo(Integer value) {
            addCriterion("adminid <=", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidIn(List<Integer> values) {
            addCriterion("adminid in", values, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotIn(List<Integer> values) {
            addCriterion("adminid not in", values, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidBetween(Integer value1, Integer value2) {
            addCriterion("adminid between", value1, value2, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotBetween(Integer value1, Integer value2) {
            addCriterion("adminid not between", value1, value2, "adminid");
            return (Criteria) this;
        }

        public Criteria andLogin_typeIsNull() {
            addCriterion("login_type is null");
            return (Criteria) this;
        }

        public Criteria andLogin_typeIsNotNull() {
            addCriterion("login_type is not null");
            return (Criteria) this;
        }

        public Criteria andLogin_typeEqualTo(String value) {
            addCriterion("login_type =", value, "login_type");
            return (Criteria) this;
        }

        public Criteria andLogin_typeNotEqualTo(String value) {
            addCriterion("login_type <>", value, "login_type");
            return (Criteria) this;
        }

        public Criteria andLogin_typeGreaterThan(String value) {
            addCriterion("login_type >", value, "login_type");
            return (Criteria) this;
        }

        public Criteria andLogin_typeGreaterThanOrEqualTo(String value) {
            addCriterion("login_type >=", value, "login_type");
            return (Criteria) this;
        }

        public Criteria andLogin_typeLessThan(String value) {
            addCriterion("login_type <", value, "login_type");
            return (Criteria) this;
        }

        public Criteria andLogin_typeLessThanOrEqualTo(String value) {
            addCriterion("login_type <=", value, "login_type");
            return (Criteria) this;
        }

        public Criteria andLogin_typeLike(String value) {
            addCriterion("login_type like", value, "login_type");
            return (Criteria) this;
        }

        public Criteria andLogin_typeNotLike(String value) {
            addCriterion("login_type not like", value, "login_type");
            return (Criteria) this;
        }

        public Criteria andLogin_typeIn(List<String> values) {
            addCriterion("login_type in", values, "login_type");
            return (Criteria) this;
        }

        public Criteria andLogin_typeNotIn(List<String> values) {
            addCriterion("login_type not in", values, "login_type");
            return (Criteria) this;
        }

        public Criteria andLogin_typeBetween(String value1, String value2) {
            addCriterion("login_type between", value1, value2, "login_type");
            return (Criteria) this;
        }

        public Criteria andLogin_typeNotBetween(String value1, String value2) {
            addCriterion("login_type not between", value1, value2, "login_type");
            return (Criteria) this;
        }

        public Criteria andClerk_idIsNull() {
            addCriterion("clerk_id is null");
            return (Criteria) this;
        }

        public Criteria andClerk_idIsNotNull() {
            addCriterion("clerk_id is not null");
            return (Criteria) this;
        }

        public Criteria andClerk_idEqualTo(Integer value) {
            addCriterion("clerk_id =", value, "clerk_id");
            return (Criteria) this;
        }

        public Criteria andClerk_idNotEqualTo(Integer value) {
            addCriterion("clerk_id <>", value, "clerk_id");
            return (Criteria) this;
        }

        public Criteria andClerk_idGreaterThan(Integer value) {
            addCriterion("clerk_id >", value, "clerk_id");
            return (Criteria) this;
        }

        public Criteria andClerk_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("clerk_id >=", value, "clerk_id");
            return (Criteria) this;
        }

        public Criteria andClerk_idLessThan(Integer value) {
            addCriterion("clerk_id <", value, "clerk_id");
            return (Criteria) this;
        }

        public Criteria andClerk_idLessThanOrEqualTo(Integer value) {
            addCriterion("clerk_id <=", value, "clerk_id");
            return (Criteria) this;
        }

        public Criteria andClerk_idIn(List<Integer> values) {
            addCriterion("clerk_id in", values, "clerk_id");
            return (Criteria) this;
        }

        public Criteria andClerk_idNotIn(List<Integer> values) {
            addCriterion("clerk_id not in", values, "clerk_id");
            return (Criteria) this;
        }

        public Criteria andClerk_idBetween(Integer value1, Integer value2) {
            addCriterion("clerk_id between", value1, value2, "clerk_id");
            return (Criteria) this;
        }

        public Criteria andClerk_idNotBetween(Integer value1, Integer value2) {
            addCriterion("clerk_id not between", value1, value2, "clerk_id");
            return (Criteria) this;
        }

        public Criteria andPay_moneyIsNull() {
            addCriterion("pay_money is null");
            return (Criteria) this;
        }

        public Criteria andPay_moneyIsNotNull() {
            addCriterion("pay_money is not null");
            return (Criteria) this;
        }

        public Criteria andPay_moneyEqualTo(BigDecimal value) {
            addCriterion("pay_money =", value, "pay_money");
            return (Criteria) this;
        }

        public Criteria andPay_moneyNotEqualTo(BigDecimal value) {
            addCriterion("pay_money <>", value, "pay_money");
            return (Criteria) this;
        }

        public Criteria andPay_moneyGreaterThan(BigDecimal value) {
            addCriterion("pay_money >", value, "pay_money");
            return (Criteria) this;
        }

        public Criteria andPay_moneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pay_money >=", value, "pay_money");
            return (Criteria) this;
        }

        public Criteria andPay_moneyLessThan(BigDecimal value) {
            addCriterion("pay_money <", value, "pay_money");
            return (Criteria) this;
        }

        public Criteria andPay_moneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pay_money <=", value, "pay_money");
            return (Criteria) this;
        }

        public Criteria andPay_moneyIn(List<BigDecimal> values) {
            addCriterion("pay_money in", values, "pay_money");
            return (Criteria) this;
        }

        public Criteria andPay_moneyNotIn(List<BigDecimal> values) {
            addCriterion("pay_money not in", values, "pay_money");
            return (Criteria) this;
        }

        public Criteria andPay_moneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pay_money between", value1, value2, "pay_money");
            return (Criteria) this;
        }

        public Criteria andPay_moneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pay_money not between", value1, value2, "pay_money");
            return (Criteria) this;
        }

        public Criteria andBind_store_timeIsNull() {
            addCriterion("bind_store_time is null");
            return (Criteria) this;
        }

        public Criteria andBind_store_timeIsNotNull() {
            addCriterion("bind_store_time is not null");
            return (Criteria) this;
        }

        public Criteria andBind_store_timeEqualTo(Integer value) {
            addCriterion("bind_store_time =", value, "bind_store_time");
            return (Criteria) this;
        }

        public Criteria andBind_store_timeNotEqualTo(Integer value) {
            addCriterion("bind_store_time <>", value, "bind_store_time");
            return (Criteria) this;
        }

        public Criteria andBind_store_timeGreaterThan(Integer value) {
            addCriterion("bind_store_time >", value, "bind_store_time");
            return (Criteria) this;
        }

        public Criteria andBind_store_timeGreaterThanOrEqualTo(Integer value) {
            addCriterion("bind_store_time >=", value, "bind_store_time");
            return (Criteria) this;
        }

        public Criteria andBind_store_timeLessThan(Integer value) {
            addCriterion("bind_store_time <", value, "bind_store_time");
            return (Criteria) this;
        }

        public Criteria andBind_store_timeLessThanOrEqualTo(Integer value) {
            addCriterion("bind_store_time <=", value, "bind_store_time");
            return (Criteria) this;
        }

        public Criteria andBind_store_timeIn(List<Integer> values) {
            addCriterion("bind_store_time in", values, "bind_store_time");
            return (Criteria) this;
        }

        public Criteria andBind_store_timeNotIn(List<Integer> values) {
            addCriterion("bind_store_time not in", values, "bind_store_time");
            return (Criteria) this;
        }

        public Criteria andBind_store_timeBetween(Integer value1, Integer value2) {
            addCriterion("bind_store_time between", value1, value2, "bind_store_time");
            return (Criteria) this;
        }

        public Criteria andBind_store_timeNotBetween(Integer value1, Integer value2) {
            addCriterion("bind_store_time not between", value1, value2, "bind_store_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table live_user
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table live_user
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}