package com.live.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class LiveStoreClerkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    public LiveStoreClerkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andWx_nameIsNull() {
            addCriterion("wx_name is null");
            return (Criteria) this;
        }

        public Criteria andWx_nameIsNotNull() {
            addCriterion("wx_name is not null");
            return (Criteria) this;
        }

        public Criteria andWx_nameEqualTo(String value) {
            addCriterion("wx_name =", value, "wx_name");
            return (Criteria) this;
        }

        public Criteria andWx_nameNotEqualTo(String value) {
            addCriterion("wx_name <>", value, "wx_name");
            return (Criteria) this;
        }

        public Criteria andWx_nameGreaterThan(String value) {
            addCriterion("wx_name >", value, "wx_name");
            return (Criteria) this;
        }

        public Criteria andWx_nameGreaterThanOrEqualTo(String value) {
            addCriterion("wx_name >=", value, "wx_name");
            return (Criteria) this;
        }

        public Criteria andWx_nameLessThan(String value) {
            addCriterion("wx_name <", value, "wx_name");
            return (Criteria) this;
        }

        public Criteria andWx_nameLessThanOrEqualTo(String value) {
            addCriterion("wx_name <=", value, "wx_name");
            return (Criteria) this;
        }

        public Criteria andWx_nameLike(String value) {
            addCriterion("wx_name like", value, "wx_name");
            return (Criteria) this;
        }

        public Criteria andWx_nameNotLike(String value) {
            addCriterion("wx_name not like", value, "wx_name");
            return (Criteria) this;
        }

        public Criteria andWx_nameIn(List<String> values) {
            addCriterion("wx_name in", values, "wx_name");
            return (Criteria) this;
        }

        public Criteria andWx_nameNotIn(List<String> values) {
            addCriterion("wx_name not in", values, "wx_name");
            return (Criteria) this;
        }

        public Criteria andWx_nameBetween(String value1, String value2) {
            addCriterion("wx_name between", value1, value2, "wx_name");
            return (Criteria) this;
        }

        public Criteria andWx_nameNotBetween(String value1, String value2) {
            addCriterion("wx_name not between", value1, value2, "wx_name");
            return (Criteria) this;
        }

        public Criteria andHead_imgIsNull() {
            addCriterion("head_img is null");
            return (Criteria) this;
        }

        public Criteria andHead_imgIsNotNull() {
            addCriterion("head_img is not null");
            return (Criteria) this;
        }

        public Criteria andHead_imgEqualTo(String value) {
            addCriterion("head_img =", value, "head_img");
            return (Criteria) this;
        }

        public Criteria andHead_imgNotEqualTo(String value) {
            addCriterion("head_img <>", value, "head_img");
            return (Criteria) this;
        }

        public Criteria andHead_imgGreaterThan(String value) {
            addCriterion("head_img >", value, "head_img");
            return (Criteria) this;
        }

        public Criteria andHead_imgGreaterThanOrEqualTo(String value) {
            addCriterion("head_img >=", value, "head_img");
            return (Criteria) this;
        }

        public Criteria andHead_imgLessThan(String value) {
            addCriterion("head_img <", value, "head_img");
            return (Criteria) this;
        }

        public Criteria andHead_imgLessThanOrEqualTo(String value) {
            addCriterion("head_img <=", value, "head_img");
            return (Criteria) this;
        }

        public Criteria andHead_imgLike(String value) {
            addCriterion("head_img like", value, "head_img");
            return (Criteria) this;
        }

        public Criteria andHead_imgNotLike(String value) {
            addCriterion("head_img not like", value, "head_img");
            return (Criteria) this;
        }

        public Criteria andHead_imgIn(List<String> values) {
            addCriterion("head_img in", values, "head_img");
            return (Criteria) this;
        }

        public Criteria andHead_imgNotIn(List<String> values) {
            addCriterion("head_img not in", values, "head_img");
            return (Criteria) this;
        }

        public Criteria andHead_imgBetween(String value1, String value2) {
            addCriterion("head_img between", value1, value2, "head_img");
            return (Criteria) this;
        }

        public Criteria andHead_imgNotBetween(String value1, String value2) {
            addCriterion("head_img not between", value1, value2, "head_img");
            return (Criteria) this;
        }

        public Criteria andAdmin_idIsNull() {
            addCriterion("admin_id is null");
            return (Criteria) this;
        }

        public Criteria andAdmin_idIsNotNull() {
            addCriterion("admin_id is not null");
            return (Criteria) this;
        }

        public Criteria andAdmin_idEqualTo(Integer value) {
            addCriterion("admin_id =", value, "admin_id");
            return (Criteria) this;
        }

        public Criteria andAdmin_idNotEqualTo(Integer value) {
            addCriterion("admin_id <>", value, "admin_id");
            return (Criteria) this;
        }

        public Criteria andAdmin_idGreaterThan(Integer value) {
            addCriterion("admin_id >", value, "admin_id");
            return (Criteria) this;
        }

        public Criteria andAdmin_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("admin_id >=", value, "admin_id");
            return (Criteria) this;
        }

        public Criteria andAdmin_idLessThan(Integer value) {
            addCriterion("admin_id <", value, "admin_id");
            return (Criteria) this;
        }

        public Criteria andAdmin_idLessThanOrEqualTo(Integer value) {
            addCriterion("admin_id <=", value, "admin_id");
            return (Criteria) this;
        }

        public Criteria andAdmin_idIn(List<Integer> values) {
            addCriterion("admin_id in", values, "admin_id");
            return (Criteria) this;
        }

        public Criteria andAdmin_idNotIn(List<Integer> values) {
            addCriterion("admin_id not in", values, "admin_id");
            return (Criteria) this;
        }

        public Criteria andAdmin_idBetween(Integer value1, Integer value2) {
            addCriterion("admin_id between", value1, value2, "admin_id");
            return (Criteria) this;
        }

        public Criteria andAdmin_idNotBetween(Integer value1, Integer value2) {
            addCriterion("admin_id not between", value1, value2, "admin_id");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andStore_roleIsNull() {
            addCriterion("store_role is null");
            return (Criteria) this;
        }

        public Criteria andStore_roleIsNotNull() {
            addCriterion("store_role is not null");
            return (Criteria) this;
        }

        public Criteria andStore_roleEqualTo(Integer value) {
            addCriterion("store_role =", value, "store_role");
            return (Criteria) this;
        }

        public Criteria andStore_roleNotEqualTo(Integer value) {
            addCriterion("store_role <>", value, "store_role");
            return (Criteria) this;
        }

        public Criteria andStore_roleGreaterThan(Integer value) {
            addCriterion("store_role >", value, "store_role");
            return (Criteria) this;
        }

        public Criteria andStore_roleGreaterThanOrEqualTo(Integer value) {
            addCriterion("store_role >=", value, "store_role");
            return (Criteria) this;
        }

        public Criteria andStore_roleLessThan(Integer value) {
            addCriterion("store_role <", value, "store_role");
            return (Criteria) this;
        }

        public Criteria andStore_roleLessThanOrEqualTo(Integer value) {
            addCriterion("store_role <=", value, "store_role");
            return (Criteria) this;
        }

        public Criteria andStore_roleIn(List<Integer> values) {
            addCriterion("store_role in", values, "store_role");
            return (Criteria) this;
        }

        public Criteria andStore_roleNotIn(List<Integer> values) {
            addCriterion("store_role not in", values, "store_role");
            return (Criteria) this;
        }

        public Criteria andStore_roleBetween(Integer value1, Integer value2) {
            addCriterion("store_role between", value1, value2, "store_role");
            return (Criteria) this;
        }

        public Criteria andStore_roleNotBetween(Integer value1, Integer value2) {
            addCriterion("store_role not between", value1, value2, "store_role");
            return (Criteria) this;
        }

        public Criteria andStore_statusIsNull() {
            addCriterion("store_status is null");
            return (Criteria) this;
        }

        public Criteria andStore_statusIsNotNull() {
            addCriterion("store_status is not null");
            return (Criteria) this;
        }

        public Criteria andStore_statusEqualTo(Integer value) {
            addCriterion("store_status =", value, "store_status");
            return (Criteria) this;
        }

        public Criteria andStore_statusNotEqualTo(Integer value) {
            addCriterion("store_status <>", value, "store_status");
            return (Criteria) this;
        }

        public Criteria andStore_statusGreaterThan(Integer value) {
            addCriterion("store_status >", value, "store_status");
            return (Criteria) this;
        }

        public Criteria andStore_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("store_status >=", value, "store_status");
            return (Criteria) this;
        }

        public Criteria andStore_statusLessThan(Integer value) {
            addCriterion("store_status <", value, "store_status");
            return (Criteria) this;
        }

        public Criteria andStore_statusLessThanOrEqualTo(Integer value) {
            addCriterion("store_status <=", value, "store_status");
            return (Criteria) this;
        }

        public Criteria andStore_statusIn(List<Integer> values) {
            addCriterion("store_status in", values, "store_status");
            return (Criteria) this;
        }

        public Criteria andStore_statusNotIn(List<Integer> values) {
            addCriterion("store_status not in", values, "store_status");
            return (Criteria) this;
        }

        public Criteria andStore_statusBetween(Integer value1, Integer value2) {
            addCriterion("store_status between", value1, value2, "store_status");
            return (Criteria) this;
        }

        public Criteria andStore_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("store_status not between", value1, value2, "store_status");
            return (Criteria) this;
        }

        public Criteria andStore_idIsNull() {
            addCriterion("store_id is null");
            return (Criteria) this;
        }

        public Criteria andStore_idIsNotNull() {
            addCriterion("store_id is not null");
            return (Criteria) this;
        }

        public Criteria andStore_idEqualTo(Integer value) {
            addCriterion("store_id =", value, "store_id");
            return (Criteria) this;
        }

        public Criteria andStore_idNotEqualTo(Integer value) {
            addCriterion("store_id <>", value, "store_id");
            return (Criteria) this;
        }

        public Criteria andStore_idGreaterThan(Integer value) {
            addCriterion("store_id >", value, "store_id");
            return (Criteria) this;
        }

        public Criteria andStore_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("store_id >=", value, "store_id");
            return (Criteria) this;
        }

        public Criteria andStore_idLessThan(Integer value) {
            addCriterion("store_id <", value, "store_id");
            return (Criteria) this;
        }

        public Criteria andStore_idLessThanOrEqualTo(Integer value) {
            addCriterion("store_id <=", value, "store_id");
            return (Criteria) this;
        }

        public Criteria andStore_idIn(List<Integer> values) {
            addCriterion("store_id in", values, "store_id");
            return (Criteria) this;
        }

        public Criteria andStore_idNotIn(List<Integer> values) {
            addCriterion("store_id not in", values, "store_id");
            return (Criteria) this;
        }

        public Criteria andStore_idBetween(Integer value1, Integer value2) {
            addCriterion("store_id between", value1, value2, "store_id");
            return (Criteria) this;
        }

        public Criteria andStore_idNotBetween(Integer value1, Integer value2) {
            addCriterion("store_id not between", value1, value2, "store_id");
            return (Criteria) this;
        }

        public Criteria andParent_idIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParent_idIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParent_idEqualTo(Integer value) {
            addCriterion("parent_id =", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idNotEqualTo(Integer value) {
            addCriterion("parent_id <>", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idGreaterThan(Integer value) {
            addCriterion("parent_id >", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_id >=", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idLessThan(Integer value) {
            addCriterion("parent_id <", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idLessThanOrEqualTo(Integer value) {
            addCriterion("parent_id <=", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idIn(List<Integer> values) {
            addCriterion("parent_id in", values, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idNotIn(List<Integer> values) {
            addCriterion("parent_id not in", values, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idBetween(Integer value1, Integer value2) {
            addCriterion("parent_id between", value1, value2, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_id not between", value1, value2, "parent_id");
            return (Criteria) this;
        }

        public Criteria andNow_moneyIsNull() {
            addCriterion("now_money is null");
            return (Criteria) this;
        }

        public Criteria andNow_moneyIsNotNull() {
            addCriterion("now_money is not null");
            return (Criteria) this;
        }

        public Criteria andNow_moneyEqualTo(BigDecimal value) {
            addCriterion("now_money =", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyNotEqualTo(BigDecimal value) {
            addCriterion("now_money <>", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyGreaterThan(BigDecimal value) {
            addCriterion("now_money >", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("now_money >=", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyLessThan(BigDecimal value) {
            addCriterion("now_money <", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("now_money <=", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyIn(List<BigDecimal> values) {
            addCriterion("now_money in", values, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyNotIn(List<BigDecimal> values) {
            addCriterion("now_money not in", values, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("now_money between", value1, value2, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("now_money not between", value1, value2, "now_money");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("openid is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("openid is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("openid =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("openid <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("openid >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("openid >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("openid <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("openid <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("openid like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("openid not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("openid in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("openid not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("openid between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("openid not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeEqualTo(Integer value) {
            addCriterion("update_time =", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotEqualTo(Integer value) {
            addCriterion("update_time <>", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThan(Integer value) {
            addCriterion("update_time >", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_time >=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThan(Integer value) {
            addCriterion("update_time <", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThanOrEqualTo(Integer value) {
            addCriterion("update_time <=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIn(List<Integer> values) {
            addCriterion("update_time in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotIn(List<Integer> values) {
            addCriterion("update_time not in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeBetween(Integer value1, Integer value2) {
            addCriterion("update_time between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotBetween(Integer value1, Integer value2) {
            addCriterion("update_time not between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Integer value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Integer value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Integer> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andIs_cancellationIsNull() {
            addCriterion("is_cancellation is null");
            return (Criteria) this;
        }

        public Criteria andIs_cancellationIsNotNull() {
            addCriterion("is_cancellation is not null");
            return (Criteria) this;
        }

        public Criteria andIs_cancellationEqualTo(Boolean value) {
            addCriterion("is_cancellation =", value, "is_cancellation");
            return (Criteria) this;
        }

        public Criteria andIs_cancellationNotEqualTo(Boolean value) {
            addCriterion("is_cancellation <>", value, "is_cancellation");
            return (Criteria) this;
        }

        public Criteria andIs_cancellationGreaterThan(Boolean value) {
            addCriterion("is_cancellation >", value, "is_cancellation");
            return (Criteria) this;
        }

        public Criteria andIs_cancellationGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_cancellation >=", value, "is_cancellation");
            return (Criteria) this;
        }

        public Criteria andIs_cancellationLessThan(Boolean value) {
            addCriterion("is_cancellation <", value, "is_cancellation");
            return (Criteria) this;
        }

        public Criteria andIs_cancellationLessThanOrEqualTo(Boolean value) {
            addCriterion("is_cancellation <=", value, "is_cancellation");
            return (Criteria) this;
        }

        public Criteria andIs_cancellationIn(List<Boolean> values) {
            addCriterion("is_cancellation in", values, "is_cancellation");
            return (Criteria) this;
        }

        public Criteria andIs_cancellationNotIn(List<Boolean> values) {
            addCriterion("is_cancellation not in", values, "is_cancellation");
            return (Criteria) this;
        }

        public Criteria andIs_cancellationBetween(Boolean value1, Boolean value2) {
            addCriterion("is_cancellation between", value1, value2, "is_cancellation");
            return (Criteria) this;
        }

        public Criteria andIs_cancellationNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_cancellation not between", value1, value2, "is_cancellation");
            return (Criteria) this;
        }

        public Criteria andCash_moneyIsNull() {
            addCriterion("cash_money is null");
            return (Criteria) this;
        }

        public Criteria andCash_moneyIsNotNull() {
            addCriterion("cash_money is not null");
            return (Criteria) this;
        }

        public Criteria andCash_moneyEqualTo(BigDecimal value) {
            addCriterion("cash_money =", value, "cash_money");
            return (Criteria) this;
        }

        public Criteria andCash_moneyNotEqualTo(BigDecimal value) {
            addCriterion("cash_money <>", value, "cash_money");
            return (Criteria) this;
        }

        public Criteria andCash_moneyGreaterThan(BigDecimal value) {
            addCriterion("cash_money >", value, "cash_money");
            return (Criteria) this;
        }

        public Criteria andCash_moneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cash_money >=", value, "cash_money");
            return (Criteria) this;
        }

        public Criteria andCash_moneyLessThan(BigDecimal value) {
            addCriterion("cash_money <", value, "cash_money");
            return (Criteria) this;
        }

        public Criteria andCash_moneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cash_money <=", value, "cash_money");
            return (Criteria) this;
        }

        public Criteria andCash_moneyIn(List<BigDecimal> values) {
            addCriterion("cash_money in", values, "cash_money");
            return (Criteria) this;
        }

        public Criteria andCash_moneyNotIn(List<BigDecimal> values) {
            addCriterion("cash_money not in", values, "cash_money");
            return (Criteria) this;
        }

        public Criteria andCash_moneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cash_money between", value1, value2, "cash_money");
            return (Criteria) this;
        }

        public Criteria andCash_moneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cash_money not between", value1, value2, "cash_money");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table live_store_clerk
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}