package com.live.model;

import java.io.Serializable;

public class LiveStore extends LiveStoreKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.store_name
     *
     * @mbggenerated
     */
    private String store_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.admin_id
     *
     * @mbggenerated
     */
    private Integer admin_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.detailed_address
     *
     * @mbggenerated
     */
    private String detailed_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.store_image
     *
     * @mbggenerated
     */
    private String store_image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.day_time
     *
     * @mbggenerated
     */
    private String day_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.type_id
     *
     * @mbggenerated
     */
    private Integer type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.contact_name
     *
     * @mbggenerated
     */
    private String contact_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.province_id
     *
     * @mbggenerated
     */
    private Integer province_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.city_id
     *
     * @mbggenerated
     */
    private Integer city_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.area_id
     *
     * @mbggenerated
     */
    private Long area_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.contact_mobile
     *
     * @mbggenerated
     */
    private String contact_mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.parent_no
     *
     * @mbggenerated
     */
    private String parent_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.store_sort
     *
     * @mbggenerated
     */
    private Integer store_sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.store_status
     *
     * @mbggenerated
     */
    private Integer store_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.is_cancellation
     *
     * @mbggenerated
     */
    private Integer is_cancellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.create_time
     *
     * @mbggenerated
     */
    private Integer create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_store.update_time
     *
     * @mbggenerated
     */
    private Integer update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live_store
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.store_name
     *
     * @return the value of live_store.store_name
     *
     * @mbggenerated
     */
    public String getStore_name() {
        return store_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.store_name
     *
     * @param store_name the value for live_store.store_name
     *
     * @mbggenerated
     */
    public void setStore_name(String store_name) {
        this.store_name = store_name == null ? null : store_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.admin_id
     *
     * @return the value of live_store.admin_id
     *
     * @mbggenerated
     */
    public Integer getAdmin_id() {
        return admin_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.admin_id
     *
     * @param admin_id the value for live_store.admin_id
     *
     * @mbggenerated
     */
    public void setAdmin_id(Integer admin_id) {
        this.admin_id = admin_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.introduction
     *
     * @return the value of live_store.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.introduction
     *
     * @param introduction the value for live_store.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.detailed_address
     *
     * @return the value of live_store.detailed_address
     *
     * @mbggenerated
     */
    public String getDetailed_address() {
        return detailed_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.detailed_address
     *
     * @param detailed_address the value for live_store.detailed_address
     *
     * @mbggenerated
     */
    public void setDetailed_address(String detailed_address) {
        this.detailed_address = detailed_address == null ? null : detailed_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.store_image
     *
     * @return the value of live_store.store_image
     *
     * @mbggenerated
     */
    public String getStore_image() {
        return store_image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.store_image
     *
     * @param store_image the value for live_store.store_image
     *
     * @mbggenerated
     */
    public void setStore_image(String store_image) {
        this.store_image = store_image == null ? null : store_image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.latitude
     *
     * @return the value of live_store.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.latitude
     *
     * @param latitude the value for live_store.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.longitude
     *
     * @return the value of live_store.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.longitude
     *
     * @param longitude the value for live_store.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.day_time
     *
     * @return the value of live_store.day_time
     *
     * @mbggenerated
     */
    public String getDay_time() {
        return day_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.day_time
     *
     * @param day_time the value for live_store.day_time
     *
     * @mbggenerated
     */
    public void setDay_time(String day_time) {
        this.day_time = day_time == null ? null : day_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.type_id
     *
     * @return the value of live_store.type_id
     *
     * @mbggenerated
     */
    public Integer getType_id() {
        return type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.type_id
     *
     * @param type_id the value for live_store.type_id
     *
     * @mbggenerated
     */
    public void setType_id(Integer type_id) {
        this.type_id = type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.contact_name
     *
     * @return the value of live_store.contact_name
     *
     * @mbggenerated
     */
    public String getContact_name() {
        return contact_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.contact_name
     *
     * @param contact_name the value for live_store.contact_name
     *
     * @mbggenerated
     */
    public void setContact_name(String contact_name) {
        this.contact_name = contact_name == null ? null : contact_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.province_id
     *
     * @return the value of live_store.province_id
     *
     * @mbggenerated
     */
    public Integer getProvince_id() {
        return province_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.province_id
     *
     * @param province_id the value for live_store.province_id
     *
     * @mbggenerated
     */
    public void setProvince_id(Integer province_id) {
        this.province_id = province_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.city_id
     *
     * @return the value of live_store.city_id
     *
     * @mbggenerated
     */
    public Integer getCity_id() {
        return city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.city_id
     *
     * @param city_id the value for live_store.city_id
     *
     * @mbggenerated
     */
    public void setCity_id(Integer city_id) {
        this.city_id = city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.area_id
     *
     * @return the value of live_store.area_id
     *
     * @mbggenerated
     */
    public Long getArea_id() {
        return area_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.area_id
     *
     * @param area_id the value for live_store.area_id
     *
     * @mbggenerated
     */
    public void setArea_id(Long area_id) {
        this.area_id = area_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.contact_mobile
     *
     * @return the value of live_store.contact_mobile
     *
     * @mbggenerated
     */
    public String getContact_mobile() {
        return contact_mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.contact_mobile
     *
     * @param contact_mobile the value for live_store.contact_mobile
     *
     * @mbggenerated
     */
    public void setContact_mobile(String contact_mobile) {
        this.contact_mobile = contact_mobile == null ? null : contact_mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.parent_no
     *
     * @return the value of live_store.parent_no
     *
     * @mbggenerated
     */
    public String getParent_no() {
        return parent_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.parent_no
     *
     * @param parent_no the value for live_store.parent_no
     *
     * @mbggenerated
     */
    public void setParent_no(String parent_no) {
        this.parent_no = parent_no == null ? null : parent_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.store_sort
     *
     * @return the value of live_store.store_sort
     *
     * @mbggenerated
     */
    public Integer getStore_sort() {
        return store_sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.store_sort
     *
     * @param store_sort the value for live_store.store_sort
     *
     * @mbggenerated
     */
    public void setStore_sort(Integer store_sort) {
        this.store_sort = store_sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.store_status
     *
     * @return the value of live_store.store_status
     *
     * @mbggenerated
     */
    public Integer getStore_status() {
        return store_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.store_status
     *
     * @param store_status the value for live_store.store_status
     *
     * @mbggenerated
     */
    public void setStore_status(Integer store_status) {
        this.store_status = store_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.is_cancellation
     *
     * @return the value of live_store.is_cancellation
     *
     * @mbggenerated
     */
    public Integer getIs_cancellation() {
        return is_cancellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.is_cancellation
     *
     * @param is_cancellation the value for live_store.is_cancellation
     *
     * @mbggenerated
     */
    public void setIs_cancellation(Integer is_cancellation) {
        this.is_cancellation = is_cancellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.create_time
     *
     * @return the value of live_store.create_time
     *
     * @mbggenerated
     */
    public Integer getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.create_time
     *
     * @param create_time the value for live_store.create_time
     *
     * @mbggenerated
     */
    public void setCreate_time(Integer create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_store.update_time
     *
     * @return the value of live_store.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_store.update_time
     *
     * @param update_time the value for live_store.update_time
     *
     * @mbggenerated
     */
    public void setUpdate_time(Integer update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", store_name=").append(store_name);
        sb.append(", admin_id=").append(admin_id);
        sb.append(", introduction=").append(introduction);
        sb.append(", detailed_address=").append(detailed_address);
        sb.append(", store_image=").append(store_image);
        sb.append(", latitude=").append(latitude);
        sb.append(", longitude=").append(longitude);
        sb.append(", day_time=").append(day_time);
        sb.append(", type_id=").append(type_id);
        sb.append(", contact_name=").append(contact_name);
        sb.append(", province_id=").append(province_id);
        sb.append(", city_id=").append(city_id);
        sb.append(", area_id=").append(area_id);
        sb.append(", contact_mobile=").append(contact_mobile);
        sb.append(", parent_no=").append(parent_no);
        sb.append(", store_sort=").append(store_sort);
        sb.append(", store_status=").append(store_status);
        sb.append(", is_cancellation=").append(is_cancellation);
        sb.append(", create_time=").append(create_time);
        sb.append(", update_time=").append(update_time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}