package com.live.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class LiveWechatUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    public LiveWechatUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidIsNull() {
            addCriterion("`uid` is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("`uid` is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("`uid` =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("`uid` <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("`uid` >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("`uid` >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("`uid` <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("`uid` <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("`uid` in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("`uid` not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("`uid` between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("`uid` not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidIsNull() {
            addCriterion("routine_openid is null");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidIsNotNull() {
            addCriterion("routine_openid is not null");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidEqualTo(String value) {
            addCriterion("routine_openid =", value, "routine_openid");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidNotEqualTo(String value) {
            addCriterion("routine_openid <>", value, "routine_openid");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidGreaterThan(String value) {
            addCriterion("routine_openid >", value, "routine_openid");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidGreaterThanOrEqualTo(String value) {
            addCriterion("routine_openid >=", value, "routine_openid");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidLessThan(String value) {
            addCriterion("routine_openid <", value, "routine_openid");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidLessThanOrEqualTo(String value) {
            addCriterion("routine_openid <=", value, "routine_openid");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidLike(String value) {
            addCriterion("routine_openid like", value, "routine_openid");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidNotLike(String value) {
            addCriterion("routine_openid not like", value, "routine_openid");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidIn(List<String> values) {
            addCriterion("routine_openid in", values, "routine_openid");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidNotIn(List<String> values) {
            addCriterion("routine_openid not in", values, "routine_openid");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidBetween(String value1, String value2) {
            addCriterion("routine_openid between", value1, value2, "routine_openid");
            return (Criteria) this;
        }

        public Criteria andRoutine_openidNotBetween(String value1, String value2) {
            addCriterion("routine_openid not between", value1, value2, "routine_openid");
            return (Criteria) this;
        }

        public Criteria andUnionidIsNull() {
            addCriterion("unionid is null");
            return (Criteria) this;
        }

        public Criteria andUnionidIsNotNull() {
            addCriterion("unionid is not null");
            return (Criteria) this;
        }

        public Criteria andUnionidEqualTo(String value) {
            addCriterion("unionid =", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidNotEqualTo(String value) {
            addCriterion("unionid <>", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidGreaterThan(String value) {
            addCriterion("unionid >", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidGreaterThanOrEqualTo(String value) {
            addCriterion("unionid >=", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidLessThan(String value) {
            addCriterion("unionid <", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidLessThanOrEqualTo(String value) {
            addCriterion("unionid <=", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidLike(String value) {
            addCriterion("unionid like", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidNotLike(String value) {
            addCriterion("unionid not like", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidIn(List<String> values) {
            addCriterion("unionid in", values, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidNotIn(List<String> values) {
            addCriterion("unionid not in", values, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidBetween(String value1, String value2) {
            addCriterion("unionid between", value1, value2, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidNotBetween(String value1, String value2) {
            addCriterion("unionid not between", value1, value2, "unionid");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("openid is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("openid is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("openid =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("openid <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("openid >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("openid >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("openid <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("openid <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("openid like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("openid not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("openid in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("openid not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("openid between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("openid not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlIsNull() {
            addCriterion("headimgurl is null");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlIsNotNull() {
            addCriterion("headimgurl is not null");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlEqualTo(String value) {
            addCriterion("headimgurl =", value, "headimgurl");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlNotEqualTo(String value) {
            addCriterion("headimgurl <>", value, "headimgurl");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlGreaterThan(String value) {
            addCriterion("headimgurl >", value, "headimgurl");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlGreaterThanOrEqualTo(String value) {
            addCriterion("headimgurl >=", value, "headimgurl");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlLessThan(String value) {
            addCriterion("headimgurl <", value, "headimgurl");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlLessThanOrEqualTo(String value) {
            addCriterion("headimgurl <=", value, "headimgurl");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlLike(String value) {
            addCriterion("headimgurl like", value, "headimgurl");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlNotLike(String value) {
            addCriterion("headimgurl not like", value, "headimgurl");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlIn(List<String> values) {
            addCriterion("headimgurl in", values, "headimgurl");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlNotIn(List<String> values) {
            addCriterion("headimgurl not in", values, "headimgurl");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlBetween(String value1, String value2) {
            addCriterion("headimgurl between", value1, value2, "headimgurl");
            return (Criteria) this;
        }

        public Criteria andHeadimgurlNotBetween(String value1, String value2) {
            addCriterion("headimgurl not between", value1, value2, "headimgurl");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Integer value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Integer value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Integer value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Integer value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Integer value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Integer> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Integer> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Integer value1, Integer value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Integer value1, Integer value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("`language` is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("`language` is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(String value) {
            addCriterion("`language` =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(String value) {
            addCriterion("`language` <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(String value) {
            addCriterion("`language` >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("`language` >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(String value) {
            addCriterion("`language` <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(String value) {
            addCriterion("`language` <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLike(String value) {
            addCriterion("`language` like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotLike(String value) {
            addCriterion("`language` not like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<String> values) {
            addCriterion("`language` in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<String> values) {
            addCriterion("`language` not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(String value1, String value2) {
            addCriterion("`language` between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(String value1, String value2) {
            addCriterion("`language` not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andGroupidIsNull() {
            addCriterion("groupid is null");
            return (Criteria) this;
        }

        public Criteria andGroupidIsNotNull() {
            addCriterion("groupid is not null");
            return (Criteria) this;
        }

        public Criteria andGroupidEqualTo(Short value) {
            addCriterion("groupid =", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotEqualTo(Short value) {
            addCriterion("groupid <>", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidGreaterThan(Short value) {
            addCriterion("groupid >", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidGreaterThanOrEqualTo(Short value) {
            addCriterion("groupid >=", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLessThan(Short value) {
            addCriterion("groupid <", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLessThanOrEqualTo(Short value) {
            addCriterion("groupid <=", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidIn(List<Short> values) {
            addCriterion("groupid in", values, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotIn(List<Short> values) {
            addCriterion("groupid not in", values, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidBetween(Short value1, Short value2) {
            addCriterion("groupid between", value1, value2, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotBetween(Short value1, Short value2) {
            addCriterion("groupid not between", value1, value2, "groupid");
            return (Criteria) this;
        }

        public Criteria andTagid_listIsNull() {
            addCriterion("tagid_list is null");
            return (Criteria) this;
        }

        public Criteria andTagid_listIsNotNull() {
            addCriterion("tagid_list is not null");
            return (Criteria) this;
        }

        public Criteria andTagid_listEqualTo(String value) {
            addCriterion("tagid_list =", value, "tagid_list");
            return (Criteria) this;
        }

        public Criteria andTagid_listNotEqualTo(String value) {
            addCriterion("tagid_list <>", value, "tagid_list");
            return (Criteria) this;
        }

        public Criteria andTagid_listGreaterThan(String value) {
            addCriterion("tagid_list >", value, "tagid_list");
            return (Criteria) this;
        }

        public Criteria andTagid_listGreaterThanOrEqualTo(String value) {
            addCriterion("tagid_list >=", value, "tagid_list");
            return (Criteria) this;
        }

        public Criteria andTagid_listLessThan(String value) {
            addCriterion("tagid_list <", value, "tagid_list");
            return (Criteria) this;
        }

        public Criteria andTagid_listLessThanOrEqualTo(String value) {
            addCriterion("tagid_list <=", value, "tagid_list");
            return (Criteria) this;
        }

        public Criteria andTagid_listLike(String value) {
            addCriterion("tagid_list like", value, "tagid_list");
            return (Criteria) this;
        }

        public Criteria andTagid_listNotLike(String value) {
            addCriterion("tagid_list not like", value, "tagid_list");
            return (Criteria) this;
        }

        public Criteria andTagid_listIn(List<String> values) {
            addCriterion("tagid_list in", values, "tagid_list");
            return (Criteria) this;
        }

        public Criteria andTagid_listNotIn(List<String> values) {
            addCriterion("tagid_list not in", values, "tagid_list");
            return (Criteria) this;
        }

        public Criteria andTagid_listBetween(String value1, String value2) {
            addCriterion("tagid_list between", value1, value2, "tagid_list");
            return (Criteria) this;
        }

        public Criteria andTagid_listNotBetween(String value1, String value2) {
            addCriterion("tagid_list not between", value1, value2, "tagid_list");
            return (Criteria) this;
        }

        public Criteria andSubscribeIsNull() {
            addCriterion("subscribe is null");
            return (Criteria) this;
        }

        public Criteria andSubscribeIsNotNull() {
            addCriterion("subscribe is not null");
            return (Criteria) this;
        }

        public Criteria andSubscribeEqualTo(Integer value) {
            addCriterion("subscribe =", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeNotEqualTo(Integer value) {
            addCriterion("subscribe <>", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeGreaterThan(Integer value) {
            addCriterion("subscribe >", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeGreaterThanOrEqualTo(Integer value) {
            addCriterion("subscribe >=", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeLessThan(Integer value) {
            addCriterion("subscribe <", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeLessThanOrEqualTo(Integer value) {
            addCriterion("subscribe <=", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeIn(List<Integer> values) {
            addCriterion("subscribe in", values, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeNotIn(List<Integer> values) {
            addCriterion("subscribe not in", values, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeBetween(Integer value1, Integer value2) {
            addCriterion("subscribe between", value1, value2, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeNotBetween(Integer value1, Integer value2) {
            addCriterion("subscribe not between", value1, value2, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribe_timeIsNull() {
            addCriterion("subscribe_time is null");
            return (Criteria) this;
        }

        public Criteria andSubscribe_timeIsNotNull() {
            addCriterion("subscribe_time is not null");
            return (Criteria) this;
        }

        public Criteria andSubscribe_timeEqualTo(Integer value) {
            addCriterion("subscribe_time =", value, "subscribe_time");
            return (Criteria) this;
        }

        public Criteria andSubscribe_timeNotEqualTo(Integer value) {
            addCriterion("subscribe_time <>", value, "subscribe_time");
            return (Criteria) this;
        }

        public Criteria andSubscribe_timeGreaterThan(Integer value) {
            addCriterion("subscribe_time >", value, "subscribe_time");
            return (Criteria) this;
        }

        public Criteria andSubscribe_timeGreaterThanOrEqualTo(Integer value) {
            addCriterion("subscribe_time >=", value, "subscribe_time");
            return (Criteria) this;
        }

        public Criteria andSubscribe_timeLessThan(Integer value) {
            addCriterion("subscribe_time <", value, "subscribe_time");
            return (Criteria) this;
        }

        public Criteria andSubscribe_timeLessThanOrEqualTo(Integer value) {
            addCriterion("subscribe_time <=", value, "subscribe_time");
            return (Criteria) this;
        }

        public Criteria andSubscribe_timeIn(List<Integer> values) {
            addCriterion("subscribe_time in", values, "subscribe_time");
            return (Criteria) this;
        }

        public Criteria andSubscribe_timeNotIn(List<Integer> values) {
            addCriterion("subscribe_time not in", values, "subscribe_time");
            return (Criteria) this;
        }

        public Criteria andSubscribe_timeBetween(Integer value1, Integer value2) {
            addCriterion("subscribe_time between", value1, value2, "subscribe_time");
            return (Criteria) this;
        }

        public Criteria andSubscribe_timeNotBetween(Integer value1, Integer value2) {
            addCriterion("subscribe_time not between", value1, value2, "subscribe_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAdd_timeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAdd_timeEqualTo(Integer value) {
            addCriterion("add_time =", value, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeNotEqualTo(Integer value) {
            addCriterion("add_time <>", value, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeGreaterThan(Integer value) {
            addCriterion("add_time >", value, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeGreaterThanOrEqualTo(Integer value) {
            addCriterion("add_time >=", value, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeLessThan(Integer value) {
            addCriterion("add_time <", value, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeLessThanOrEqualTo(Integer value) {
            addCriterion("add_time <=", value, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeIn(List<Integer> values) {
            addCriterion("add_time in", values, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeNotIn(List<Integer> values) {
            addCriterion("add_time not in", values, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeBetween(Integer value1, Integer value2) {
            addCriterion("add_time between", value1, value2, "add_time");
            return (Criteria) this;
        }

        public Criteria andAdd_timeNotBetween(Integer value1, Integer value2) {
            addCriterion("add_time not between", value1, value2, "add_time");
            return (Criteria) this;
        }

        public Criteria andStairIsNull() {
            addCriterion("stair is null");
            return (Criteria) this;
        }

        public Criteria andStairIsNotNull() {
            addCriterion("stair is not null");
            return (Criteria) this;
        }

        public Criteria andStairEqualTo(Integer value) {
            addCriterion("stair =", value, "stair");
            return (Criteria) this;
        }

        public Criteria andStairNotEqualTo(Integer value) {
            addCriterion("stair <>", value, "stair");
            return (Criteria) this;
        }

        public Criteria andStairGreaterThan(Integer value) {
            addCriterion("stair >", value, "stair");
            return (Criteria) this;
        }

        public Criteria andStairGreaterThanOrEqualTo(Integer value) {
            addCriterion("stair >=", value, "stair");
            return (Criteria) this;
        }

        public Criteria andStairLessThan(Integer value) {
            addCriterion("stair <", value, "stair");
            return (Criteria) this;
        }

        public Criteria andStairLessThanOrEqualTo(Integer value) {
            addCriterion("stair <=", value, "stair");
            return (Criteria) this;
        }

        public Criteria andStairIn(List<Integer> values) {
            addCriterion("stair in", values, "stair");
            return (Criteria) this;
        }

        public Criteria andStairNotIn(List<Integer> values) {
            addCriterion("stair not in", values, "stair");
            return (Criteria) this;
        }

        public Criteria andStairBetween(Integer value1, Integer value2) {
            addCriterion("stair between", value1, value2, "stair");
            return (Criteria) this;
        }

        public Criteria andStairNotBetween(Integer value1, Integer value2) {
            addCriterion("stair not between", value1, value2, "stair");
            return (Criteria) this;
        }

        public Criteria andSecondIsNull() {
            addCriterion("`second` is null");
            return (Criteria) this;
        }

        public Criteria andSecondIsNotNull() {
            addCriterion("`second` is not null");
            return (Criteria) this;
        }

        public Criteria andSecondEqualTo(Integer value) {
            addCriterion("`second` =", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondNotEqualTo(Integer value) {
            addCriterion("`second` <>", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondGreaterThan(Integer value) {
            addCriterion("`second` >", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondGreaterThanOrEqualTo(Integer value) {
            addCriterion("`second` >=", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondLessThan(Integer value) {
            addCriterion("`second` <", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondLessThanOrEqualTo(Integer value) {
            addCriterion("`second` <=", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondIn(List<Integer> values) {
            addCriterion("`second` in", values, "second");
            return (Criteria) this;
        }

        public Criteria andSecondNotIn(List<Integer> values) {
            addCriterion("`second` not in", values, "second");
            return (Criteria) this;
        }

        public Criteria andSecondBetween(Integer value1, Integer value2) {
            addCriterion("`second` between", value1, value2, "second");
            return (Criteria) this;
        }

        public Criteria andSecondNotBetween(Integer value1, Integer value2) {
            addCriterion("`second` not between", value1, value2, "second");
            return (Criteria) this;
        }

        public Criteria andOrder_stairIsNull() {
            addCriterion("order_stair is null");
            return (Criteria) this;
        }

        public Criteria andOrder_stairIsNotNull() {
            addCriterion("order_stair is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_stairEqualTo(Integer value) {
            addCriterion("order_stair =", value, "order_stair");
            return (Criteria) this;
        }

        public Criteria andOrder_stairNotEqualTo(Integer value) {
            addCriterion("order_stair <>", value, "order_stair");
            return (Criteria) this;
        }

        public Criteria andOrder_stairGreaterThan(Integer value) {
            addCriterion("order_stair >", value, "order_stair");
            return (Criteria) this;
        }

        public Criteria andOrder_stairGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_stair >=", value, "order_stair");
            return (Criteria) this;
        }

        public Criteria andOrder_stairLessThan(Integer value) {
            addCriterion("order_stair <", value, "order_stair");
            return (Criteria) this;
        }

        public Criteria andOrder_stairLessThanOrEqualTo(Integer value) {
            addCriterion("order_stair <=", value, "order_stair");
            return (Criteria) this;
        }

        public Criteria andOrder_stairIn(List<Integer> values) {
            addCriterion("order_stair in", values, "order_stair");
            return (Criteria) this;
        }

        public Criteria andOrder_stairNotIn(List<Integer> values) {
            addCriterion("order_stair not in", values, "order_stair");
            return (Criteria) this;
        }

        public Criteria andOrder_stairBetween(Integer value1, Integer value2) {
            addCriterion("order_stair between", value1, value2, "order_stair");
            return (Criteria) this;
        }

        public Criteria andOrder_stairNotBetween(Integer value1, Integer value2) {
            addCriterion("order_stair not between", value1, value2, "order_stair");
            return (Criteria) this;
        }

        public Criteria andOrder_secondIsNull() {
            addCriterion("order_second is null");
            return (Criteria) this;
        }

        public Criteria andOrder_secondIsNotNull() {
            addCriterion("order_second is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_secondEqualTo(Integer value) {
            addCriterion("order_second =", value, "order_second");
            return (Criteria) this;
        }

        public Criteria andOrder_secondNotEqualTo(Integer value) {
            addCriterion("order_second <>", value, "order_second");
            return (Criteria) this;
        }

        public Criteria andOrder_secondGreaterThan(Integer value) {
            addCriterion("order_second >", value, "order_second");
            return (Criteria) this;
        }

        public Criteria andOrder_secondGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_second >=", value, "order_second");
            return (Criteria) this;
        }

        public Criteria andOrder_secondLessThan(Integer value) {
            addCriterion("order_second <", value, "order_second");
            return (Criteria) this;
        }

        public Criteria andOrder_secondLessThanOrEqualTo(Integer value) {
            addCriterion("order_second <=", value, "order_second");
            return (Criteria) this;
        }

        public Criteria andOrder_secondIn(List<Integer> values) {
            addCriterion("order_second in", values, "order_second");
            return (Criteria) this;
        }

        public Criteria andOrder_secondNotIn(List<Integer> values) {
            addCriterion("order_second not in", values, "order_second");
            return (Criteria) this;
        }

        public Criteria andOrder_secondBetween(Integer value1, Integer value2) {
            addCriterion("order_second between", value1, value2, "order_second");
            return (Criteria) this;
        }

        public Criteria andOrder_secondNotBetween(Integer value1, Integer value2) {
            addCriterion("order_second not between", value1, value2, "order_second");
            return (Criteria) this;
        }

        public Criteria andNow_moneyIsNull() {
            addCriterion("now_money is null");
            return (Criteria) this;
        }

        public Criteria andNow_moneyIsNotNull() {
            addCriterion("now_money is not null");
            return (Criteria) this;
        }

        public Criteria andNow_moneyEqualTo(BigDecimal value) {
            addCriterion("now_money =", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyNotEqualTo(BigDecimal value) {
            addCriterion("now_money <>", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyGreaterThan(BigDecimal value) {
            addCriterion("now_money >", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("now_money >=", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyLessThan(BigDecimal value) {
            addCriterion("now_money <", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("now_money <=", value, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyIn(List<BigDecimal> values) {
            addCriterion("now_money in", values, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyNotIn(List<BigDecimal> values) {
            addCriterion("now_money not in", values, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("now_money between", value1, value2, "now_money");
            return (Criteria) this;
        }

        public Criteria andNow_moneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("now_money not between", value1, value2, "now_money");
            return (Criteria) this;
        }

        public Criteria andSession_keyIsNull() {
            addCriterion("session_key is null");
            return (Criteria) this;
        }

        public Criteria andSession_keyIsNotNull() {
            addCriterion("session_key is not null");
            return (Criteria) this;
        }

        public Criteria andSession_keyEqualTo(String value) {
            addCriterion("session_key =", value, "session_key");
            return (Criteria) this;
        }

        public Criteria andSession_keyNotEqualTo(String value) {
            addCriterion("session_key <>", value, "session_key");
            return (Criteria) this;
        }

        public Criteria andSession_keyGreaterThan(String value) {
            addCriterion("session_key >", value, "session_key");
            return (Criteria) this;
        }

        public Criteria andSession_keyGreaterThanOrEqualTo(String value) {
            addCriterion("session_key >=", value, "session_key");
            return (Criteria) this;
        }

        public Criteria andSession_keyLessThan(String value) {
            addCriterion("session_key <", value, "session_key");
            return (Criteria) this;
        }

        public Criteria andSession_keyLessThanOrEqualTo(String value) {
            addCriterion("session_key <=", value, "session_key");
            return (Criteria) this;
        }

        public Criteria andSession_keyLike(String value) {
            addCriterion("session_key like", value, "session_key");
            return (Criteria) this;
        }

        public Criteria andSession_keyNotLike(String value) {
            addCriterion("session_key not like", value, "session_key");
            return (Criteria) this;
        }

        public Criteria andSession_keyIn(List<String> values) {
            addCriterion("session_key in", values, "session_key");
            return (Criteria) this;
        }

        public Criteria andSession_keyNotIn(List<String> values) {
            addCriterion("session_key not in", values, "session_key");
            return (Criteria) this;
        }

        public Criteria andSession_keyBetween(String value1, String value2) {
            addCriterion("session_key between", value1, value2, "session_key");
            return (Criteria) this;
        }

        public Criteria andSession_keyNotBetween(String value1, String value2) {
            addCriterion("session_key not between", value1, value2, "session_key");
            return (Criteria) this;
        }

        public Criteria andUser_typeIsNull() {
            addCriterion("user_type is null");
            return (Criteria) this;
        }

        public Criteria andUser_typeIsNotNull() {
            addCriterion("user_type is not null");
            return (Criteria) this;
        }

        public Criteria andUser_typeEqualTo(String value) {
            addCriterion("user_type =", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeNotEqualTo(String value) {
            addCriterion("user_type <>", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeGreaterThan(String value) {
            addCriterion("user_type >", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeGreaterThanOrEqualTo(String value) {
            addCriterion("user_type >=", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeLessThan(String value) {
            addCriterion("user_type <", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeLessThanOrEqualTo(String value) {
            addCriterion("user_type <=", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeLike(String value) {
            addCriterion("user_type like", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeNotLike(String value) {
            addCriterion("user_type not like", value, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeIn(List<String> values) {
            addCriterion("user_type in", values, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeNotIn(List<String> values) {
            addCriterion("user_type not in", values, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeBetween(String value1, String value2) {
            addCriterion("user_type between", value1, value2, "user_type");
            return (Criteria) this;
        }

        public Criteria andUser_typeNotBetween(String value1, String value2) {
            addCriterion("user_type not between", value1, value2, "user_type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table live_wechat_user
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table live_wechat_user
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}