package com.live.dao;

import com.live.model.LiveUser;
import com.live.model.LiveUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiveUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    int countByExample(LiveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    int deleteByExample(LiveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    int insert(LiveUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    int insertSelective(LiveUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    List<LiveUser> selectByExample(LiveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    LiveUser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LiveUser record, @Param("example") LiveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LiveUser record, @Param("example") LiveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LiveUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LiveUser record);
}