package com.live.dao;

import com.live.model.LiveStoreTree;
import com.live.model.LiveStoreTreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiveStoreTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_tree
     *
     * @mbggenerated
     */
    int countByExample(LiveStoreTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_tree
     *
     * @mbggenerated
     */
    int deleteByExample(LiveStoreTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_tree
     *
     * @mbggenerated
     */
    int insert(LiveStoreTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_tree
     *
     * @mbggenerated
     */
    int insertSelective(LiveStoreTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_tree
     *
     * @mbggenerated
     */
    List<LiveStoreTree> selectByExample(LiveStoreTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_tree
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LiveStoreTree record, @Param("example") LiveStoreTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_tree
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LiveStoreTree record, @Param("example") LiveStoreTreeExample example);
}