package com.live.dao;

import com.live.model.LiveActivityExclude;
import com.live.model.LiveActivityExcludeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiveActivityExcludeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_activity_exclude
     *
     * @mbggenerated
     */
    int countByExample(LiveActivityExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_activity_exclude
     *
     * @mbggenerated
     */
    int deleteByExample(LiveActivityExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_activity_exclude
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_activity_exclude
     *
     * @mbggenerated
     */
    int insert(LiveActivityExclude record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_activity_exclude
     *
     * @mbggenerated
     */
    int insertSelective(LiveActivityExclude record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_activity_exclude
     *
     * @mbggenerated
     */
    List<LiveActivityExclude> selectByExample(LiveActivityExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_activity_exclude
     *
     * @mbggenerated
     */
    LiveActivityExclude selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_activity_exclude
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LiveActivityExclude record, @Param("example") LiveActivityExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_activity_exclude
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LiveActivityExclude record, @Param("example") LiveActivityExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_activity_exclude
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LiveActivityExclude record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_activity_exclude
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LiveActivityExclude record);
}