package com.live.dao;

import com.live.model.LiveStoreClerk;
import com.live.model.LiveStoreClerkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiveStoreClerkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    int countByExample(LiveStoreClerkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    int deleteByExample(LiveStoreClerkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    int insert(LiveStoreClerk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    int insertSelective(LiveStoreClerk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    List<LiveStoreClerk> selectByExample(LiveStoreClerkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    LiveStoreClerk selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LiveStoreClerk record, @Param("example") LiveStoreClerkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LiveStoreClerk record, @Param("example") LiveStoreClerkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LiveStoreClerk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_store_clerk
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LiveStoreClerk record);
}